ALTER TABLE
  `payment` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `trade_no` bigint NULL COMMENT '交易单号',
  MODIFY COLUMN `order_no` bigint NULL COMMENT '订单号',
  MODIFY COLUMN `account_id` bigint NULL COMMENT '客户id',
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT '客户名称',
  MODIFY COLUMN `pay_amount` bigint NULL COMMENT '支付金额',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT '商品金额',
  MODIFY COLUMN `consume_type` int NULL COMMENT '消费类型',
  MODIFY COLUMN `pay_state` int NULL COMMENT '支付状态',
  MODIFY COLUMN `tripartite_trade_no` varchar(255) NULL COMMENT '三方交易单号',
  MODIFY COLUMN `order_info` json NULL COMMENT '订单信息',
  MODIFY COLUMN `payee_info` json NULL COMMENT '收款方信息(嵌套 Money 由 MoneyCentJsonSerializer 按分存取)',
  MODIFY COLUMN `pay_time` datetime NULL COMMENT '支付时间',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '支付单';
