CREATE TABLE `payment` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `trade_no` bigint NULL COMMENT '交易单号',
  `order_no` bigint NULL COMMENT '订单号',
  `account_id` bigint NULL COMMENT '客户id',
  `account_name` varchar(255) NULL COMMENT '客户名称',
  `pay_amount` bigint NULL COMMENT '支付金额',
  `goods_amount` bigint NULL COMMENT '商品金额',
  `consume_type` int NULL COMMENT '消费类型',
  `pay_state` int NULL COMMENT '支付状态',
  `tripartite_trade_no` varchar(255) NULL COMMENT '三方交易单号',
  `order_info` json NULL COMMENT '订单信息',
  `payee_info` json NULL COMMENT '收款方信息',
  `pay_time` datetime NULL COMMENT '支付时间',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_payment_account_id`(`account_id`) COMMENT '客户id',
  INDEX `auto_idx_payment_consume_type`(`consume_type`) COMMENT '消费类型',
  INDEX `auto_idx_payment_order_no`(`order_no`) COMMENT '订单号',
  INDEX `auto_idx_payment_pay_time`(`pay_time`) COMMENT '支付时间',
  INDEX `auto_idx_payment_trade_no`(`trade_no`) COMMENT '交易单号'
) COMMENT = '支付单';
