ALTER TABLE
  `payment` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `trade_no` bigint NULL COMMENT 'tradeNo',
  MODIFY COLUMN `order_no` bigint NULL COMMENT 'orderNo',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT 'accountName',
  MODIFY COLUMN `pay_amount` bigint NULL COMMENT 'payAmount',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT 'goodsAmount',
  MODIFY COLUMN `consume_type` int NULL COMMENT 'consumeType',
  MODIFY COLUMN `pay_state` int NULL COMMENT 'payState',
  MODIFY COLUMN `tripartite_trade_no` varchar(255) NULL COMMENT 'tripartiteTradeNo',
  MODIFY COLUMN `order_info` json NULL COMMENT 'orderInfo',
  MODIFY COLUMN `payee_info` json NULL COMMENT 'payeeInfo',
  MODIFY COLUMN `pay_time` datetime NULL COMMENT 'payTime',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'PaymentDO表';
