ALTER TABLE
  `channel` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT 'name',
  MODIFY COLUMN `state` int NULL COMMENT 'state',
  MODIFY COLUMN `company_info` varchar(255) NULL COMMENT 'companyInfo',
  MODIFY COLUMN `audit_refuse_reason` varchar(255) NULL COMMENT 'auditRefuseReason',
  MODIFY COLUMN `store_permission` int NULL COMMENT 'storePermission[1是,0否]',
  MODIFY COLUMN `ship_province_code` int NULL COMMENT 'shipProvinceCode',
  MODIFY COLUMN `ship_city_code` int NULL COMMENT 'shipCityCode',
  MODIFY COLUMN `ship_area_code` int NULL COMMENT 'shipAreaCode',
  MODIFY COLUMN `contacts_way` varchar(255) NULL COMMENT 'contactsWay',
  MODIFY COLUMN `contacts_name` varchar(255) NULL COMMENT 'contactsName',
  MODIFY COLUMN `store_name` varchar(255) NULL COMMENT 'storeName',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'ChannelDO表';
