ALTER TABLE
  `channel` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '名称(源 account.realname)',
  MODIFY COLUMN `state` int NULL COMMENT '状态',
  MODIFY COLUMN `company_info` varchar(255) NULL COMMENT '企业信息',
  MODIFY COLUMN `audit_refuse_reason` varchar(255) NULL COMMENT '审批拒绝原因',
  MODIFY COLUMN `store_permission` int NULL COMMENT '数字门店权限[1是,0否]',
  MODIFY COLUMN `ship_province_code` int NULL COMMENT '店铺地址, 省 CODE, 6 位',
  MODIFY COLUMN `ship_city_code` int NULL COMMENT '店铺地址, 市 CODE, 6 位',
  MODIFY COLUMN `ship_area_code` int NULL COMMENT '店铺地址, 区 CODE, 6 位',
  MODIFY COLUMN `contacts_way` varchar(255) NULL COMMENT '联系方式',
  MODIFY COLUMN `contacts_name` varchar(255) NULL COMMENT '联系人名称',
  MODIFY COLUMN `store_name` varchar(255) NULL COMMENT '店铺名称',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '渠道商';
