ALTER TABLE
  `channel` DROP COLUMN `up_dealer_id`,
  DROP COLUMN `up_operator_id`,
  DROP COLUMN `role_id`,
  DROP COLUMN `username`,
  DROP COLUMN `role_name`,
  DROP COLUMN `head_img`,
  DROP COLUMN `name_auth_info`,
  DROP COLUMN `audit_state`,
  DROP COLUMN `service_fee_config_v_o`,
  DROP COLUMN `dealer_earnings`,
  DROP COLUMN `wx_mp_config`,
  DROP COLUMN `license`,
  DROP COLUMN `jf_license`,
  DROP COLUMN `total_order_number`,
  DROP COLUMN `total_refund_number`,
  DROP COLUMN `total_order_amount`,
  DROP COLUMN `total_refund_amount`,
  DROP COLUMN `jf_permission`,
  DROP COLUMN `mk_permission`,
  DROP COLUMN `custom_count`,
  MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '名称(源 account.realname)' AFTER `id`,
  MODIFY COLUMN `body_type` int NULL COMMENT '主体类型',
  MODIFY COLUMN `state` int NULL COMMENT '状态',
  MODIFY COLUMN `company_info` varchar(255) NULL COMMENT '企业信息',
  MODIFY COLUMN `audit_refuse_reason` varchar(255) NULL COMMENT '审批拒绝原因' AFTER `company_info`,
  MODIFY COLUMN `market_count` int NULL COMMENT '市场数量' AFTER `audit_refuse_reason`,
  MODIFY COLUMN `store_permission` int NULL COMMENT '数字门店权限' AFTER `market_count`,
  MODIFY COLUMN `ship_province_code` int NULL COMMENT '店铺地址, 省 CODE, 6 位' AFTER `store_permission`,
  MODIFY COLUMN `ship_city_code` int NULL COMMENT '店铺地址, 市 CODE, 6 位' AFTER `ship_province_code`,
  MODIFY COLUMN `ship_area_code` int NULL COMMENT '店铺地址, 区 CODE, 6 位' AFTER `ship_city_code`,
  MODIFY COLUMN `contacts_way` varchar(255) NULL COMMENT '联系方式' AFTER `ship_area_code`,
  MODIFY COLUMN `contacts_name` varchar(255) NULL COMMENT '联系人名称' AFTER `contacts_way`,
  MODIFY COLUMN `store_name` varchar(255) NULL COMMENT '店铺名称' AFTER `contacts_name`,
  MODIFY COLUMN `channel_type` varchar(255) NULL COMMENT '渠道商类型' AFTER `store_name`,
ADD
  COLUMN `executor` json NULL COMMENT '操作人信息' AFTER `channel_type`,
ADD
  COLUMN `creator_id` bigint NULL COMMENT '创建人id' AFTER `executor`,
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
ADD
  COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
