CREATE TABLE `account_purse_alter_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `account_id` bigint NULL COMMENT '客户id',
  `account_type` int NULL COMMENT '客户类型',
  `purse_type` int NULL COMMENT '账户类型',
  `earning_alter_type` int NULL COMMENT '分润修改类型',
  `alter_type` int NULL COMMENT '变动类型',
  `amount` bigint NULL COMMENT '金额',
  `join_record_id` bigint NULL COMMENT '关联记录id',
  `remark` varchar(255) NULL COMMENT '备注或记录',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_account_purse_alter_record_account_id`(`account_id`) COMMENT '客户id',
  INDEX `auto_idx_account_purse_alter_record_account_type`(`account_type`) COMMENT '客户类型',
  INDEX `auto_idx_account_purse_alter_record_alter_type`(`alter_type`) COMMENT '变动类型',
  INDEX `auto_idx_account_purse_alter_record_join_record_id`(`join_record_id`) COMMENT '关联记录id',
  INDEX `auto_idx_account_purse_alter_record_purse_type`(`purse_type`) COMMENT '账户类型'
);
