ALTER TABLE
  `account_tripartite_purse` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `oid_user_no` varchar(255) NULL COMMENT 'oidUserNo',
  MODIFY COLUMN `oid_apply_seq_no` varchar(255) NULL COMMENT 'oidApplySeqNo',
  MODIFY COLUMN `user_status` varchar(255) NULL COMMENT 'userStatus',
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT 'accountName',
  MODIFY COLUMN `amount` bigint NULL COMMENT 'amount',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT 'remark',
  MODIFY COLUMN `account_type` varchar(255) NULL COMMENT 'accountType',
  MODIFY COLUMN `bank_name` varchar(255) NULL COMMENT 'bankName',
  MODIFY COLUMN `bank_no` varchar(255) NULL COMMENT 'bankNo',
  MODIFY COLUMN `commit_info` json NULL COMMENT 'commitInfo',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'AccountTripartitePurseDO表';
