ALTER TABLE
  `account_purse_roll_out` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT 'accountName',
  MODIFY COLUMN `account_type` int NULL COMMENT 'accountType[0会员,1供应商,2渠道商]',
  MODIFY COLUMN `purse_type` int NULL COMMENT 'purseType[0总账户,11商品分润账户,13商品货款结余账户,2采购金账户,3保证金账户,4营销账户,5商品位]',
  MODIFY COLUMN `apply_amount` bigint NULL COMMENT 'applyAmount',
  MODIFY COLUMN `audit_state` int NULL COMMENT 'auditState[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `tripartite_trade_state` int NULL COMMENT 'tripartiteTradeState[0拒绝,1通过]',
  MODIFY COLUMN `tripartite_account_id` varchar(255) NULL COMMENT 'tripartiteAccountId',
  MODIFY COLUMN `tripartite_trade_no` varchar(255) NULL COMMENT 'tripartiteTradeNo',
  MODIFY COLUMN `audit_remark` varchar(255) NULL COMMENT 'auditRemark',
  MODIFY COLUMN `audit_time` datetime NULL COMMENT 'auditTime',
  MODIFY COLUMN `handling_fee` bigint NULL COMMENT 'handlingFee',
  MODIFY COLUMN `apply_time` datetime NULL COMMENT 'applyTime',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'AccountPurseRollOutDO表';
