ALTER TABLE
  `account_purse_roll_out` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `account_id` bigint NULL COMMENT '客户id',
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT '客户名称',
  MODIFY COLUMN `account_type` int NULL COMMENT '客户类型[0会员,1供应商,2渠道商]',
  MODIFY COLUMN `purse_type` int NULL COMMENT '账户类型[0总账户,11商品分润账户,13商品货款结余账户,2采购金账户,3保证金账户,4营销账户,5商品位]',
  MODIFY COLUMN `apply_amount` bigint NULL COMMENT '申请金额',
  MODIFY COLUMN `audit_state` int NULL COMMENT '审核状态[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `tripartite_trade_state` int NULL COMMENT '三方交易状态[0拒绝,1通过]',
  MODIFY COLUMN `tripartite_account_id` varchar(255) NULL COMMENT '三方用户id',
  MODIFY COLUMN `tripartite_trade_no` varchar(255) NULL COMMENT '三方交易单号',
  MODIFY COLUMN `audit_remark` varchar(255) NULL COMMENT '审核备注',
  MODIFY COLUMN `audit_time` datetime NULL COMMENT '审核时间',
  MODIFY COLUMN `handling_fee` bigint NULL COMMENT '手续费',
  MODIFY COLUMN `apply_time` datetime NULL COMMENT '申请时间',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
