CREATE TABLE `account_purse_roll_out` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `account_id` bigint NULL COMMENT '客户id',
  `account_name` varchar(255) NULL COMMENT '客户名称',
  `account_type` int NULL COMMENT '客户类型',
  `purse_type` int NULL COMMENT '账户类型',
  `apply_amount` bigint NULL COMMENT '申请金额',
  `audit_state` int NULL COMMENT '审核状态',
  `tripartite_trade_state` int NULL COMMENT '三方交易状态',
  `tripartite_account_id` varchar(255) NULL COMMENT '三方用户id',
  `tripartite_trade_no` varchar(255) NULL COMMENT '三方交易单号',
  `audit_remark` varchar(255) NULL COMMENT '审核备注',
  `audit_time` datetime NULL COMMENT '审核时间',
  `handling_fee` bigint NULL COMMENT '手续费',
  `apply_time` datetime NULL COMMENT '申请时间',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_account_purse_roll_out_account_id`(`account_id`) COMMENT '客户id',
  INDEX `auto_idx_account_purse_roll_out_account_type`(`account_type`) COMMENT '客户类型',
  INDEX `auto_idx_account_purse_roll_out_audit_time`(`audit_time`) COMMENT '审核时间',
  INDEX `auto_idx_account_purse_roll_out_purse_type`(`purse_type`) COMMENT '账户类型'
);
