CREATE TABLE `account_tripartite_purse` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `account_id` bigint NULL COMMENT '客户id',
  `oid_user_no` varchar(255) NULL COMMENT '三方用户id',
  `oid_apply_seq_no` varchar(255) NULL COMMENT '三方申请id',
  `user_status` varchar(255) NULL COMMENT '状态',
  `account_name` varchar(255) NULL COMMENT '账户姓名',
  `amount` bigint NULL COMMENT '三方账户余额',
  `remark` varchar(255) NULL COMMENT '备注',
  `account_type` varchar(255) NULL COMMENT '类型',
  `bank_name` varchar(255) NULL COMMENT '银行名称（源 account_tripartite_purse.bank_name 列）',
  `bank_no` varchar(255) NULL COMMENT '银行卡号',
  `commit_info` json NULL COMMENT '资料信息',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_account_tripartite_purse_account_id`(`account_id`) COMMENT '客户id'
);
