ALTER TABLE
  `market` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `market_level` int NULL COMMENT 'marketLevel',
  MODIFY COLUMN `market_name` varchar(255) NULL COMMENT 'marketName',
  MODIFY COLUMN `market_logo` varchar(255) NULL COMMENT 'marketLogo',
  MODIFY COLUMN `market_desc` varchar(255) NULL COMMENT 'marketDesc',
  MODIFY COLUMN `category_id` bigint NULL COMMENT 'categoryId',
  MODIFY COLUMN `goods_num` int NULL COMMENT 'goodsNum',
  MODIFY COLUMN `sub_bind_num` int NULL COMMENT 'subBindNum',
  MODIFY COLUMN `sell_num` int NULL COMMENT 'sellNum',
  MODIFY COLUMN `sell_amount` bigint NULL COMMENT 'sellAmount',
  MODIFY COLUMN `client_id` bigint NULL COMMENT 'clientId',
  MODIFY COLUMN `market_type` varchar(9) NULL COMMENT 'marketType[GENERAL普通市场,SPECIAL专区市场,GOLD_ZONE黄金专区]',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'MarketDO表';
