ALTER TABLE
  `ship_address` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `ship_area` varchar(255) NULL COMMENT 'shipArea',
  MODIFY COLUMN `ship_name` varchar(255) NULL COMMENT 'shipName',
  MODIFY COLUMN `ship_address` varchar(255) NULL COMMENT 'shipAddress',
  MODIFY COLUMN `ship_phone` bigint NULL COMMENT 'shipPhone',
  MODIFY COLUMN `ship_zip_code` varchar(255) NULL COMMENT 'shipZipCode',
  MODIFY COLUMN `ship_province_code` int NULL COMMENT 'shipProvinceCode',
  MODIFY COLUMN `ship_city_code` int NULL COMMENT 'shipCityCode',
  MODIFY COLUMN `ship_area_code` int NULL COMMENT 'shipAreaCode',
  MODIFY COLUMN `is_default` int NULL COMMENT 'isDefault',
  MODIFY COLUMN `identity` int NULL COMMENT 'identity[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'ShipAddressDO表';
