CREATE TABLE `sku_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NULL COMMENT '交易单ID',
  `spu_order_id` bigint NULL COMMENT 'SPU订单ID',
  `goods_amount` bigint NULL COMMENT '选品金额',
  `store_amount` bigint NULL COMMENT '铺货金额',
  `freight_amount` bigint NULL COMMENT '运费金额',
  `discount_amount` bigint NULL COMMENT '优惠金额',
  `total_amount` bigint NULL COMMENT '总金额',
  `supplier_amount` bigint NULL COMMENT '货款金额',
  `order_state` int NULL COMMENT '订单状态',
  `dealer_id` bigint NULL COMMENT '交易师ID',
  `operator_id` bigint NULL COMMENT '运营商ID',
  `supplier_id` bigint NULL COMMENT '供应商ID',
  `settlement_config_v_o` json NULL COMMENT '结算配置(源列 settlement_config_v_o, 多来源 JSON 故用 String)',
  `spu_id` bigint NULL COMMENT 'spuID',
  `sku_id` bigint NULL COMMENT 'skuID',
  `out_sku_id` varchar(255) NULL COMMENT '外部SkuId',
  `count` int NULL COMMENT '购买数量',
  `spu_name` varchar(255) NULL COMMENT 'spu名称',
  `sku_img` varchar(255) NULL COMMENT 'sku图片',
  `sku_sale_attribute` json NULL COMMENT 'sku销售属性',
  `sku_name` varchar(255) NULL COMMENT 'sku名称',
  `sku_weight` double(6, 2) NULL COMMENT 'sku重量(千克)',
  `sku_volume` double(6, 2) NULL COMMENT 'sku体积(m3)',
  `sku_supplier_price` bigint NULL COMMENT 'sku供货价',
  `sku_sale_price` bigint NULL COMMENT 'sku采购价',
  `sku_store_price` bigint NULL COMMENT 'sku铺货价',
  `deliver_count` int NULL COMMENT '发货数量',
  `refunding_count` int NULL COMMENT '售后中数量',
  `refunded_count` int NULL COMMENT '已售后数量',
  `order_state_log` varchar(255) NULL COMMENT '订单状态流转日志(逗号隔开)',
  `delivered_time` datetime NULL COMMENT '发货完成时间',
  `receive_time` datetime NULL COMMENT '确认收货时间',
  `settle_order_type` int NULL COMMENT '结算节点',
  `settle_send_state` int NULL COMMENT '结算发送状态',
  `total_service_change` bigint NULL COMMENT '总服务费',
  `operator_service_change` bigint NULL COMMENT '运营商服务费',
  `operator_real_ratio` double(6, 2) NULL COMMENT '运营商实际服务比例',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_sku_order_dealer_id`(`dealer_id`) COMMENT '交易师ID',
  INDEX `auto_idx_sku_order_operator_id`(`operator_id`) COMMENT '运营商ID',
  INDEX `auto_idx_sku_order_order_id`(`order_id`) COMMENT '交易单ID',
  INDEX `auto_idx_sku_order_order_state`(`order_state`) COMMENT '订单状态',
  INDEX `auto_idx_sku_order_sku_id`(`sku_id`) COMMENT 'skuID',
  INDEX `auto_idx_sku_order_spu_id`(`spu_id`) COMMENT 'spuID',
  INDEX `auto_idx_sku_order_spu_order_id`(`spu_order_id`) COMMENT 'SPU订单ID',
  INDEX `auto_idx_sku_order_supplier_id`(`supplier_id`) COMMENT '供应商ID'
);
