ALTER TABLE
  `sku_order` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `order_id` bigint NULL COMMENT 'orderId',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'spuOrderId',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT 'goodsAmount',
  MODIFY COLUMN `store_amount` bigint NULL COMMENT 'storeAmount',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT 'freightAmount',
  MODIFY COLUMN `discount_amount` bigint NULL COMMENT 'discountAmount',
  MODIFY COLUMN `total_amount` bigint NULL COMMENT 'totalAmount',
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT 'supplierAmount',
  MODIFY COLUMN `order_state` int NULL COMMENT 'orderState[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `dealer_id` bigint NULL COMMENT 'dealerId',
  MODIFY COLUMN `operator_id` bigint NULL COMMENT 'operatorId',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT 'supplierId',
  MODIFY COLUMN `settlement_config_v_o` json NULL COMMENT 'settlementConfigVO',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'spuId',
  MODIFY COLUMN `sku_id` bigint NULL COMMENT 'skuId',
  MODIFY COLUMN `out_sku_id` varchar(255) NULL COMMENT 'outSkuId',
  MODIFY COLUMN `count` int NULL COMMENT 'count',
  MODIFY COLUMN `spu_name` varchar(255) NULL COMMENT 'spuName',
  MODIFY COLUMN `sku_img` varchar(255) NULL COMMENT 'skuImg',
  MODIFY COLUMN `sku_sale_attribute` json NULL COMMENT 'skuSaleAttribute',
  MODIFY COLUMN `sku_name` varchar(255) NULL COMMENT 'skuName',
  MODIFY COLUMN `sku_weight` double(6, 2) NULL COMMENT 'skuWeight',
  MODIFY COLUMN `sku_volume` double(6, 2) NULL COMMENT 'skuVolume',
  MODIFY COLUMN `sku_supplier_price` bigint NULL COMMENT 'skuSupplierPrice',
  MODIFY COLUMN `sku_sale_price` bigint NULL COMMENT 'skuSalePrice',
  MODIFY COLUMN `sku_store_price` bigint NULL COMMENT 'skuStorePrice',
  MODIFY COLUMN `deliver_count` int NULL COMMENT 'deliverCount',
  MODIFY COLUMN `refunding_count` int NULL COMMENT 'refundingCount',
  MODIFY COLUMN `refunded_count` int NULL COMMENT 'refundedCount',
  MODIFY COLUMN `order_state_log` varchar(255) NULL COMMENT 'orderStateLog',
  MODIFY COLUMN `delivered_time` datetime NULL COMMENT 'deliveredTime',
  MODIFY COLUMN `receive_time` datetime NULL COMMENT 'receiveTime',
  MODIFY COLUMN `settle_order_type` int NULL COMMENT 'settleOrderType',
  MODIFY COLUMN `settle_send_state` int NULL COMMENT 'settleSendState[1是,0否]',
  MODIFY COLUMN `total_service_change` bigint NULL COMMENT 'totalServiceChange',
  MODIFY COLUMN `operator_service_change` bigint NULL COMMENT 'operatorServiceChange',
  MODIFY COLUMN `operator_real_ratio` double(6, 2) NULL COMMENT 'operatorRealRatio',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'SkuOrderDO表';
