CREATE TABLE `store_goods` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `goods_id` bigint NULL COMMENT '商品id',
  `sku_id` bigint NULL COMMENT 'skuId',
  `market_id` bigint NULL COMMENT '来源',
  `data_type` int NULL COMMENT '数据类型(0：商品  1：sku)',
  `sell_price` bigint NULL COMMENT '销售价(Money，落库 BIGINT 分)',
  `sell_num` int NULL COMMENT '销量',
  `store_id` bigint NULL COMMENT '门店id',
  `goods_state` int NULL COMMENT '商品状态[0上架,1下架,-1平台下架,2待上架,3平台门店下架]',
  `channel_id` bigint NULL COMMENT '渠道商id',
  `unit_price` bigint NULL COMMENT '零售价(Money，落库 BIGINT 分)',
  `supplier_price` bigint NULL COMMENT '供货价(Money，落库 BIGINT 分)',
  `goods_info` varchar(255) NULL COMMENT '商品信息',
  `need_update` int NULL COMMENT '是否需要更新(0不需要，1需要)',
  `recommendation_time` datetime NULL COMMENT '推荐时间',
  `up_time` datetime NULL COMMENT '上架时间',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_store_goods_channel_id`(`channel_id`) COMMENT '渠道商id',
  INDEX `auto_idx_store_goods_goods_id`(`goods_id`) COMMENT '商品id',
  INDEX `auto_idx_store_goods_goods_state`(`goods_state`) COMMENT '商品状态',
  INDEX `auto_idx_store_goods_market_id`(`market_id`) COMMENT '来源',
  INDEX `auto_idx_store_goods_sku_id`(`sku_id`) COMMENT 'skuId',
  INDEX `auto_idx_store_goods_store_id`(`store_id`) COMMENT '门店id'
);
