ALTER TABLE
  `store_distribution` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `goods_id` bigint NULL COMMENT '商品id',
  MODIFY COLUMN `market_id` bigint NULL COMMENT '来源',
  MODIFY COLUMN `data_type` int NULL COMMENT '数据类型(0：商品  1：sku)',
  MODIFY COLUMN `sell_price` bigint NULL COMMENT '销售价(Money，落库 BIGINT 分)',
  MODIFY COLUMN `sell_num` int NULL COMMENT '销量',
  MODIFY COLUMN `store_id` bigint NULL COMMENT '门店id',
  MODIFY COLUMN `goods_state` int NULL COMMENT '商品状态[0上架,1下架,-1平台下架,2待上架,3平台门店下架]',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT '渠道商id',
  MODIFY COLUMN `unit_price` bigint NULL COMMENT '零售价(Money，落库 BIGINT 分)',
  MODIFY COLUMN `supplier_price` bigint NULL COMMENT '供货价(Money，落库 BIGINT 分)',
  MODIFY COLUMN `goods_info` varchar(255) NULL COMMENT '商品信息',
  MODIFY COLUMN `need_update` int NULL COMMENT '是否需要更新(0不需要，1需要)',
  MODIFY COLUMN `recommendation_time` datetime NULL COMMENT '推荐时间',
  MODIFY COLUMN `up_time` datetime NULL COMMENT '上架时间',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
