ALTER TABLE
  `store_distribution` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `goods_id` bigint NULL COMMENT 'goodsId',
  MODIFY COLUMN `market_id` bigint NULL COMMENT 'marketId',
  MODIFY COLUMN `data_type` int NULL COMMENT 'dataType',
  MODIFY COLUMN `sell_price` bigint NULL COMMENT 'sellPrice',
  MODIFY COLUMN `sell_num` int NULL COMMENT 'sellNum',
  MODIFY COLUMN `store_id` bigint NULL COMMENT 'storeId',
  MODIFY COLUMN `goods_state` int NULL COMMENT 'goodsState[0上架,1下架,-1平台下架,2待上架,3平台门店下架]',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT 'channelId',
  MODIFY COLUMN `unit_price` bigint NULL COMMENT 'unitPrice',
  MODIFY COLUMN `supplier_price` bigint NULL COMMENT 'supplierPrice',
  MODIFY COLUMN `goods_info` varchar(255) NULL COMMENT 'goodsInfo',
  MODIFY COLUMN `need_update` int NULL COMMENT 'needUpdate',
  MODIFY COLUMN `recommendation_time` datetime NULL COMMENT 'recommendationTime',
  MODIFY COLUMN `up_time` datetime NULL COMMENT 'upTime',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'StoreDistributionDO表';
