<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.newzkl.platform.Base.core</groupId>
        <artifactId>core-mybatis</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>core-mybatis-infrastructure</artifactId>
    <packaging>jar</packaging>
    <name>core-mybatis-infrastructure</name>
    <description>MyBatis 的 infrastructure 实现</description>

    <dependencies>
        <dependency>
            <groupId>com.newzkl.platform.Base</groupId>
            <artifactId>core-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>com.newzkl.platform.Base</groupId>
            <artifactId>ddd-model</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.mpe</groupId>
            <artifactId>mybatis-plus-ext-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
    </dependencies>
</project>