<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.newzkl.platform.Base</groupId>
        <artifactId>biz</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>biz-media</artifactId>
    <packaging>pom</packaging>
    <name>biz-media</name>
    <modules>
        <module>biz-media-model</module>
        <module>biz-media-facade</module>
        <module>biz-media-domain</module>
        <module>biz-media-application</module>
        <module>biz-media-infrastructure</module>
    </modules>
</project>
