ALTER TABLE
  `order` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `order_no` varchar(255) NULL COMMENT 'orderNo',
  MODIFY COLUMN `order_type` int NULL COMMENT 'orderType[0渠道商选品下单,1c端铺货下单,2运营商礼包下单]',
  MODIFY COLUMN `out_order_no` varchar(255) NULL COMMENT 'outOrderNo',
  MODIFY COLUMN `platform_type` varchar(255) NULL COMMENT 'platformType',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT 'channelId',
  MODIFY COLUMN `spu_id` varchar(255) NULL COMMENT 'spuId',
  MODIFY COLUMN `ship_v_o` json NULL COMMENT 'shipVO',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT 'remark',
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT 'supplierAmount',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT 'goodsAmount',
  MODIFY COLUMN `store_amount` bigint NULL COMMENT 'storeAmount',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT 'freightAmount',
  MODIFY COLUMN `service_amount` bigint NULL COMMENT 'serviceAmount',
  MODIFY COLUMN `total_amount` bigint NULL COMMENT 'totalAmount',
  MODIFY COLUMN `member_amount` bigint NULL COMMENT 'memberAmount',
  MODIFY COLUMN `order_state` int NULL COMMENT 'orderState[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `member_pay_state` int NULL COMMENT 'memberPayState[1是,0否]',
  MODIFY COLUMN `channel_pay_state` int NULL COMMENT 'channelPayState[1是,0否]',
  MODIFY COLUMN `pay_time` datetime NULL COMMENT 'payTime',
  MODIFY COLUMN `pay_type` int NULL COMMENT 'payType[0直接,1微信,2支付宝,3采购金,4兑换码]',
  MODIFY COLUMN `order_state_log` varchar(255) NULL COMMENT 'orderStateLog',
  MODIFY COLUMN `order_snap_v_o` json NULL COMMENT 'orderSnapVO',
  MODIFY COLUMN `store_id` bigint NULL COMMENT 'storeId',
  MODIFY COLUMN `member_id` bigint NULL COMMENT 'memberId',
  MODIFY COLUMN `close_time` datetime NULL COMMENT 'closeTime',
  MODIFY COLUMN `refund` int NULL COMMENT 'refund[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'OrderDO表';
