ALTER TABLE
  `order_state_record` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `order_id` bigint NULL COMMENT 'orderId',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'spuOrderId',
  MODIFY COLUMN `sku_order_id` bigint NULL COMMENT 'skuOrderId',
  MODIFY COLUMN `before_order_state` int NULL COMMENT 'beforeOrderState[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `after_order_state` int NULL COMMENT 'afterOrderState[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `orderer_id` bigint NULL COMMENT 'ordererId',
  MODIFY COLUMN `operator_role` int NULL COMMENT 'operatorRole[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `ext` json NULL COMMENT 'ext',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'OrderStateRecordDO表';
