ALTER TABLE
  `order` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `order_no` varchar(255) NULL COMMENT '交易单号',
  MODIFY COLUMN `order_type` int NULL COMMENT '订单类型[0渠道商选品下单,1c端铺货下单,2运营商礼包下单]',
  MODIFY COLUMN `out_order_no` varchar(255) NULL COMMENT '外部订单号',
  MODIFY COLUMN `platform_type` varchar(255) NULL COMMENT '外部平台来源(三方单来源, 非外部单为 null)',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT '渠道商ID',
  MODIFY COLUMN `spu_id` varchar(255) NULL COMMENT 'spuId(String 冗余, 为多 spu 下单兼容 (当前仅单 spu))',
  MODIFY COLUMN `ship_v_o` json NULL COMMENT '收货信息',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT '订单备注',
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT '货款金额',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT '选品金额',
  MODIFY COLUMN `store_amount` bigint NULL COMMENT '铺货金额',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT '选品运费',
  MODIFY COLUMN `service_amount` bigint NULL COMMENT '服务费: 渠道商应付',
  MODIFY COLUMN `total_amount` bigint NULL COMMENT '渠道商待支付金额',
  MODIFY COLUMN `member_amount` bigint NULL COMMENT 'C端待支付金额',
  MODIFY COLUMN `order_state` int NULL COMMENT '订单状态[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `member_pay_state` int NULL COMMENT 'C端支付状态[1是,0否]',
  MODIFY COLUMN `channel_pay_state` int NULL COMMENT '渠道商支付状态[1是,0否]',
  MODIFY COLUMN `pay_time` datetime NULL COMMENT '支付时间',
  MODIFY COLUMN `pay_type` int NULL COMMENT '支付方式[0直接,1微信,2支付宝,3采购金,4兑换码]',
  MODIFY COLUMN `order_state_log` varchar(255) NULL COMMENT '订单状态流转日志(逗号分隔)',
  MODIFY COLUMN `order_snap_v_o` json NULL COMMENT '订单快照',
  MODIFY COLUMN `store_id` bigint NULL COMMENT '门店ID',
  MODIFY COLUMN `member_id` bigint NULL COMMENT 'C端会员ID',
  MODIFY COLUMN `close_time` datetime NULL COMMENT '关闭时间',
  MODIFY COLUMN `refund` int NULL COMMENT '是否有售后[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
