CREATE TABLE `order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(255) NULL COMMENT '交易单号',
  `order_type` int NULL COMMENT '订单类型',
  `out_order_no` varchar(255) NULL COMMENT '外部订单号',
  `platform_type` varchar(255) NULL COMMENT '外部平台来源(三方单来源, 非外部单为 null)',
  `channel_id` bigint NULL COMMENT '渠道商ID',
  `spu_id` varchar(255) NULL COMMENT 'spuId(String 冗余, 为多 spu 下单兼容 (当前仅单 spu))',
  `ship_v_o` json NULL COMMENT '收货信息',
  `remark` varchar(255) NULL COMMENT '订单备注',
  `supplier_amount` bigint NULL COMMENT '货款金额',
  `goods_amount` bigint NULL COMMENT '选品金额',
  `store_amount` bigint NULL COMMENT '铺货金额',
  `freight_amount` bigint NULL COMMENT '选品运费',
  `service_amount` bigint NULL COMMENT '服务费: 渠道商应付',
  `total_amount` bigint NULL COMMENT '渠道商待支付金额',
  `member_amount` bigint NULL COMMENT 'C端待支付金额',
  `order_state` int NULL COMMENT '订单状态',
  `member_pay_state` int NULL COMMENT 'C端支付状态',
  `channel_pay_state` int NULL COMMENT '渠道商支付状态',
  `pay_time` datetime NULL COMMENT '支付时间',
  `pay_type` int NULL COMMENT '支付方式',
  `order_state_log` varchar(255) NULL COMMENT '订单状态流转日志(逗号分隔)',
  `order_snap_v_o` json NULL COMMENT '订单快照',
  `store_id` bigint NULL COMMENT '门店ID',
  `member_id` bigint NULL COMMENT 'C端会员ID',
  `close_time` datetime NULL COMMENT '关闭时间',
  `refund` int NULL COMMENT '是否有售后',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_order_channel_id`(`channel_id`) COMMENT '渠道商ID',
  INDEX `auto_idx_order_member_id`(`member_id`) COMMENT 'C端会员ID',
  INDEX `auto_idx_order_order_state`(`order_state`) COMMENT '订单状态',
  INDEX `auto_idx_order_pay_time`(`pay_time`) COMMENT '支付时间',
  INDEX `auto_idx_order_store_id`(`store_id`) COMMENT '门店ID',
  UNIQUE INDEX `auto_idx_order_order_no`(`order_no`) COMMENT '交易单号'
);
