ALTER TABLE
  `purchase_record` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `purchase_no` varchar(255) NULL COMMENT 'purchaseNo',
  MODIFY COLUMN `type` int NULL COMMENT 'type[0门店,1席位,1课程]',
  MODIFY COLUMN `trade_no` bigint NULL COMMENT 'tradeNo',
  MODIFY COLUMN `order_no` bigint NULL COMMENT 'orderNo',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT 'accountName',
  MODIFY COLUMN `pay_amount` bigint NULL COMMENT 'payAmount',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT 'goodsAmount',
  MODIFY COLUMN `pay_type` int NULL COMMENT 'payType[0直接,1微信,2支付宝,3采购金,4兑换码]',
  MODIFY COLUMN `pay_state` int NULL COMMENT 'payState[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `tripartite_trade_no` varchar(255) NULL COMMENT 'tripartiteTradeNo',
  MODIFY COLUMN `foreign_id` bigint NULL COMMENT 'foreignId',
  MODIFY COLUMN `order_info` json NULL COMMENT 'orderInfo',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'PurchaseRecordDO表';
