ALTER TABLE
  `purchase_record` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `purchase_no` varchar(255) NULL COMMENT '购买单号',
  MODIFY COLUMN `type` int NULL COMMENT '购买类型[0门店,1席位,1课程]',
  MODIFY COLUMN `trade_no` bigint NULL COMMENT '交易单号',
  MODIFY COLUMN `order_no` bigint NULL COMMENT '订单号',
  MODIFY COLUMN `account_id` bigint NULL COMMENT '客户id',
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT '客户名称',
  MODIFY COLUMN `pay_amount` bigint NULL COMMENT '支付金额',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT '商品金额',
  MODIFY COLUMN `pay_type` int NULL COMMENT '支付方式[0直接,1微信,2支付宝,3采购金,4兑换码]',
  MODIFY COLUMN `pay_state` int NULL COMMENT '支付状态[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `tripartite_trade_no` varchar(255) NULL COMMENT '三方交易单号',
  MODIFY COLUMN `foreign_id` bigint NULL COMMENT '外键id',
  MODIFY COLUMN `order_info` json NULL COMMENT '订单信息',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '购买记录 #pay';
