<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.newzkl.platform.Base</groupId>
        <artifactId>ddd</artifactId>
        <version>${base.revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd-infrastructure</artifactId>
    <packaging>jar</packaging>
    <name>ddd-infrastructure</name>
    <description>BaseRepositoryImpl / getLw 基类(BaseLambdaQueryWrapper) / BaseDO</description>

    <dependencies>
        <dependency>
            <groupId>com.newzkl.platform.Base</groupId>
            <artifactId>ddd-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.newzkl.platform.Base</groupId>
            <artifactId>core-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.newzkl.platform.Base</groupId>
            <artifactId>ddd-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>com.newzkl.platform.Base.core</groupId>
            <artifactId>core-mybatis-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.newzkl.platform.Base.core</groupId>
            <artifactId>core-job-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.newzkl.platform.Base.core</groupId>
            <artifactId>core-mq-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.newzkl.platform.Base.core</groupId>
            <artifactId>core-db-migrate-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
