CREATE TABLE `pack_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `account_id` bigint NULL COMMENT '下单账号ID',
  `ship` json NULL COMMENT '收货信息',
  `pack_id` bigint NULL COMMENT '礼包商品ID',
  `pack_type` bigint NULL COMMENT '礼包类型',
  `pack_level` int NULL COMMENT '礼包等级',
  `level_name` varchar(255) NULL COMMENT '礼包名称',
  `amount` bigint NULL COMMENT '订单金额',
  `freight_company` varchar(255) NULL COMMENT '物流公司',
  `freight_code` varchar(255) NULL COMMENT '物流单号',
  `pack_order_item_list` json NULL COMMENT '订单明细',
  `deliver_time` datetime NULL COMMENT '发货时间',
  `last_freight_api_use_time` datetime NULL COMMENT '上次物流API调用时间',
  `state` int NULL COMMENT '订单状态',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_pack_order_account_id`(`account_id`) COMMENT '下单账号ID',
  INDEX `auto_idx_pack_order_pack_id`(`pack_id`) COMMENT '礼包商品ID',
  INDEX `auto_idx_pack_order_state`(`state`) COMMENT '订单状态'
) COMMENT = '入会礼包订单(pack_order)持久化对象';
