ALTER TABLE
  `pack_order` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `account_id` bigint NULL COMMENT '下单账号ID',
  MODIFY COLUMN `ship` json NULL COMMENT '收货信息',
  MODIFY COLUMN `pack_id` bigint NULL COMMENT '礼包商品ID',
  MODIFY COLUMN `pack_type` int NULL COMMENT '礼包类型[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `pack_level` int NULL COMMENT '礼包等级',
  MODIFY COLUMN `level_name` varchar(255) NULL COMMENT '礼包名称',
  MODIFY COLUMN `amount` bigint NULL COMMENT '订单金额',
  MODIFY COLUMN `freight_company` varchar(255) NULL COMMENT '物流公司',
  MODIFY COLUMN `freight_code` varchar(255) NULL COMMENT '物流单号',
  MODIFY COLUMN `pack_order_item_list` json NULL COMMENT '订单明细',
  MODIFY COLUMN `deliver_time` datetime NULL COMMENT '发货时间',
  MODIFY COLUMN `last_freight_api_use_time` datetime NULL COMMENT '上次物流API调用时间',
  MODIFY COLUMN `state` int NULL COMMENT '订单状态',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '入会礼包订单(pack_order)持久化对象';
