ALTER TABLE
  `pack_order` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `ship` json NULL COMMENT 'ship',
  MODIFY COLUMN `pack_id` bigint NULL COMMENT 'packId',
  MODIFY COLUMN `pack_type` int NULL COMMENT 'packType[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `pack_level` int NULL COMMENT 'packLevel',
  MODIFY COLUMN `level_name` varchar(255) NULL COMMENT 'levelName',
  MODIFY COLUMN `amount` bigint NULL COMMENT 'amount',
  MODIFY COLUMN `freight_company` varchar(255) NULL COMMENT 'freightCompany',
  MODIFY COLUMN `freight_code` varchar(255) NULL COMMENT 'freightCode',
  MODIFY COLUMN `pack_order_item_list` json NULL COMMENT 'packOrderItemList',
  MODIFY COLUMN `deliver_time` datetime NULL COMMENT 'deliverTime',
  MODIFY COLUMN `last_freight_api_use_time` datetime NULL COMMENT 'lastFreightApiUseTime',
  MODIFY COLUMN `state` int NULL COMMENT 'state',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'PackOrderDO表';
