CREATE TABLE `spu_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_type` int NULL COMMENT '订单类型',
  `spu_channel_type` int NULL COMMENT '渠道类型',
  `out_order_no` varchar(255) NULL COMMENT '外部订单号',
  `order_id` bigint NULL COMMENT '交易单ID',
  `channel_id` bigint NULL COMMENT '渠道商ID',
  `supplier_id` bigint NULL COMMENT '供应商ID',
  `dealer_id` bigint NULL COMMENT '交易师ID',
  `operator_id` bigint NULL COMMENT '运营商ID',
  `spu_id` bigint NULL COMMENT 'SPU_ID',
  `spu_name` varchar(255) NULL COMMENT 'SPU名称',
  `spu_img` varchar(255) NULL COMMENT 'SPU图片',
  `sku_count` int NULL COMMENT 'SKU种类数量',
  `goods_amount` bigint NULL COMMENT '选品金额',
  `store_amount` bigint NULL COMMENT '铺货金额',
  `freight_amount` bigint NULL COMMENT '运费金额',
  `discount_amount` bigint NULL COMMENT '优惠金额',
  `total_amount` bigint NULL COMMENT '渠道商待支付总金额',
  `supplier_amount` bigint NULL COMMENT '货款金额',
  `member_amount` bigint NULL COMMENT 'C端支付金额',
  `service_amount` bigint NULL COMMENT '服务费: 渠道商应付',
  `order_state` int NULL COMMENT '订单状态',
  `ship_v_o` json NULL COMMENT '收货信息',
  `ship_phone` varchar(255) NULL COMMENT '收货人手机号',
  `remark` varchar(255) NULL COMMENT '订单备注',
  `order_state_log` varchar(255) NULL COMMENT '订单状态流转日志(逗号隔开)',
  `settle_send_state` int NULL COMMENT '运费结算发送状态',
  `store_id` bigint NULL COMMENT '门店ID',
  `member_id` bigint NULL COMMENT 'C端会员ID',
  `account_id` bigint NULL COMMENT '账号id(account.id)',
  `store_name` varchar(255) NULL COMMENT '门店名称(下单快照)',
  `store_head` varchar(255) NULL COMMENT '门店头像(下单快照)',
  `delivered_time` datetime NULL COMMENT '发货完成时间',
  `receive_time` datetime NULL COMMENT '确认收货时间',
  `close_time` datetime NULL COMMENT '关闭时间',
  `refunding_count` int NULL COMMENT '售后中数量',
  `spu_order_ext` json NULL COMMENT '订单拓展信息',
  `refund` int NULL COMMENT '是否有售后',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_spu_order_account_id`(`account_id`) COMMENT '账号id(account.id)',
  INDEX `auto_idx_spu_order_channel_id`(`channel_id`) COMMENT '渠道商ID',
  INDEX `auto_idx_spu_order_dealer_id`(`dealer_id`) COMMENT '交易师ID',
  INDEX `auto_idx_spu_order_member_id`(`member_id`) COMMENT 'C端会员ID',
  INDEX `auto_idx_spu_order_operator_id`(`operator_id`) COMMENT '运营商ID',
  INDEX `auto_idx_spu_order_order_id`(`order_id`) COMMENT '交易单ID',
  INDEX `auto_idx_spu_order_order_state`(`order_state`) COMMENT '订单状态',
  INDEX `auto_idx_spu_order_out_order_no`(`out_order_no`) COMMENT '外部订单号',
  INDEX `auto_idx_spu_order_spu_id`(`spu_id`) COMMENT 'SPU_ID',
  INDEX `auto_idx_spu_order_store_id`(`store_id`) COMMENT '门店ID',
  INDEX `auto_idx_spu_order_supplier_id`(`supplier_id`) COMMENT '供应商ID'
);
