ALTER TABLE
  `spu_order` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `order_type` int NULL COMMENT 'orderType[0渠道商选品下单,1c端铺货下单,2运营商礼包下单]',
  MODIFY COLUMN `spu_channel_type` int NULL COMMENT 'spuChannelType[0供应商商品,2外部供应链商品]',
  MODIFY COLUMN `out_order_no` varchar(255) NULL COMMENT 'outOrderNo',
  MODIFY COLUMN `order_id` bigint NULL COMMENT 'orderId',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT 'channelId',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT 'supplierId',
  MODIFY COLUMN `dealer_id` bigint NULL COMMENT 'dealerId',
  MODIFY COLUMN `operator_id` bigint NULL COMMENT 'operatorId',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'spuId',
  MODIFY COLUMN `spu_name` varchar(255) NULL COMMENT 'spuName',
  MODIFY COLUMN `spu_img` varchar(255) NULL COMMENT 'spuImg',
  MODIFY COLUMN `sku_count` int NULL COMMENT 'skuCount',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT 'goodsAmount',
  MODIFY COLUMN `store_amount` bigint NULL COMMENT 'storeAmount',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT 'freightAmount',
  MODIFY COLUMN `discount_amount` bigint NULL COMMENT 'discountAmount',
  MODIFY COLUMN `total_amount` bigint NULL COMMENT 'totalAmount',
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT 'supplierAmount',
  MODIFY COLUMN `member_amount` bigint NULL COMMENT 'memberAmount',
  MODIFY COLUMN `service_amount` bigint NULL COMMENT 'serviceAmount',
  MODIFY COLUMN `order_state` int NULL COMMENT 'orderState[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `ship_v_o` json NULL COMMENT 'shipVO',
  MODIFY COLUMN `ship_phone` varchar(255) NULL COMMENT 'shipPhone',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT 'remark',
  MODIFY COLUMN `order_state_log` varchar(255) NULL COMMENT 'orderStateLog',
  MODIFY COLUMN `settle_send_state` int NULL COMMENT 'settleSendState[1是,0否]',
  MODIFY COLUMN `store_id` bigint NULL COMMENT 'storeId',
  MODIFY COLUMN `member_id` bigint NULL COMMENT 'memberId',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `store_name` varchar(255) NULL COMMENT 'storeName',
  MODIFY COLUMN `store_head` varchar(255) NULL COMMENT 'storeHead',
  MODIFY COLUMN `delivered_time` datetime NULL COMMENT 'deliveredTime',
  MODIFY COLUMN `receive_time` datetime NULL COMMENT 'receiveTime',
  MODIFY COLUMN `close_time` datetime NULL COMMENT 'closeTime',
  MODIFY COLUMN `refunding_count` int NULL COMMENT 'refundingCount',
  MODIFY COLUMN `spu_order_ext` json NULL COMMENT 'spuOrderExt',
  MODIFY COLUMN `refund` int NULL COMMENT 'refund[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'SpuOrderDO表';
