ALTER TABLE
  `spu_order` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `order_type` int NULL COMMENT '订单类型[0渠道商选品下单,1c端铺货下单,2运营商礼包下单]',
  MODIFY COLUMN `spu_channel_type` int NULL COMMENT '渠道类型[0供应商商品,2外部供应链商品]',
  MODIFY COLUMN `out_order_no` varchar(255) NULL COMMENT '外部订单号',
  MODIFY COLUMN `order_id` bigint NULL COMMENT '交易单ID',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT '渠道商ID',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT '供应商ID',
  MODIFY COLUMN `dealer_id` bigint NULL COMMENT '交易师ID',
  MODIFY COLUMN `operator_id` bigint NULL COMMENT '运营商ID',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'SPU_ID',
  MODIFY COLUMN `spu_name` varchar(255) NULL COMMENT 'SPU名称',
  MODIFY COLUMN `spu_img` varchar(255) NULL COMMENT 'SPU图片',
  MODIFY COLUMN `sku_count` int NULL COMMENT 'SKU种类数量',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT '选品金额',
  MODIFY COLUMN `store_amount` bigint NULL COMMENT '铺货金额',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT '运费金额',
  MODIFY COLUMN `discount_amount` bigint NULL COMMENT '优惠金额',
  MODIFY COLUMN `total_amount` bigint NULL COMMENT '渠道商待支付总金额',
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT '货款金额',
  MODIFY COLUMN `member_amount` bigint NULL COMMENT 'C端支付金额',
  MODIFY COLUMN `service_amount` bigint NULL COMMENT '服务费: 渠道商应付',
  MODIFY COLUMN `order_state` int NULL COMMENT '订单状态[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `ship_v_o` json NULL COMMENT '收货信息',
  MODIFY COLUMN `ship_phone` varchar(255) NULL COMMENT '收货人手机号',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT '订单备注',
  MODIFY COLUMN `order_state_log` varchar(255) NULL COMMENT '订单状态流转日志(逗号隔开)',
  MODIFY COLUMN `settle_send_state` int NULL COMMENT '运费结算发送状态[1是,0否]',
  MODIFY COLUMN `store_id` bigint NULL COMMENT '门店ID',
  MODIFY COLUMN `member_id` bigint NULL COMMENT 'C端会员ID',
  MODIFY COLUMN `account_id` bigint NULL COMMENT '账号id(account.id)',
  MODIFY COLUMN `store_name` varchar(255) NULL COMMENT '门店名称(下单快照)',
  MODIFY COLUMN `store_head` varchar(255) NULL COMMENT '门店头像(下单快照)',
  MODIFY COLUMN `delivered_time` datetime NULL COMMENT '发货完成时间',
  MODIFY COLUMN `receive_time` datetime NULL COMMENT '确认收货时间',
  MODIFY COLUMN `close_time` datetime NULL COMMENT '关闭时间',
  MODIFY COLUMN `refunding_count` int NULL COMMENT '售后中数量',
  MODIFY COLUMN `spu_order_ext` json NULL COMMENT '订单拓展信息',
  MODIFY COLUMN `refund` int NULL COMMENT '是否有售后[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
