CREATE TABLE `spu` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `name` varchar(255) NULL COMMENT '名称(查询)',
  `title` varchar(255) NULL COMMENT '标题(查询)',
  `scroll_img` text NULL COMMENT '轮播图',
  `img` varchar(255) NULL COMMENT '图片',
  `video` varchar(255) NULL COMMENT '视频',
  `detail` text NULL COMMENT '详情',
  `account_id` bigint NULL COMMENT '账号ID',
  `category_id` bigint NULL COMMENT '所属平台分类',
  `brand_id` bigint NULL COMMENT '品牌id',
  `freight_template_id` bigint NULL COMMENT '运费模板id',
  `deliver_time_type` int NULL COMMENT '发货时效类型',
  `max_deliver_day` int NULL COMMENT '最大发货天数',
  `state` int NULL COMMENT '状态',
  `code` varchar(255) NULL COMMENT '编码',
  `market_price` bigint NULL COMMENT '市场价',
  `supply_price` bigint NULL COMMENT '供货价',
  `sale_price` bigint NULL COMMENT '销售价',
  `unit_price` bigint NULL COMMENT '销售价',
  `sale_num` int NULL COMMENT '总销量',
  `virtual_sale_num` int NULL COMMENT '虚拟销量',
  `channel_type` int NULL COMMENT '渠道类型',
  `out_spu_id` varchar(255) NULL COMMENT '外部供应链商品ID',
  `identity` bigint NULL COMMENT '角色ID',
  `audit_state` int NULL COMMENT '审批状态',
  `last_refuse_reason` varchar(255) NULL COMMENT '最后拒绝原因(状态变更至待用户提交前的最后一次拒绝原因)',
  `flow_id` bigint NULL COMMENT '审批流ID',
  `out_state` int NULL COMMENT '外部商品状态(0 已上架，1 已下架)',
  `expand` json NULL COMMENT '扩展字段(JSON, 存 categoryName/brandName/accountName/marketPriceBegan/marketPriceEnd/salePriceBegan/salePriceEnd/supplierPriceBegan/supplierPriceEnd)',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_spu_account_id`(`account_id`) COMMENT '账号ID',
  INDEX `auto_idx_spu_brand_id`(`brand_id`) COMMENT '品牌id',
  INDEX `auto_idx_spu_category_id`(`category_id`) COMMENT '所属平台分类',
  INDEX `auto_idx_spu_freight_template_id`(`freight_template_id`) COMMENT '运费模板id',
  INDEX `auto_idx_spu_name`(`name`) COMMENT '名称',
  INDEX `auto_idx_spu_state`(`state`) COMMENT '状态'
) COMMENT = 'spu';
