ALTER TABLE
  `spu` DROP COLUMN `inventory`,
  MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '名称(查询)' AFTER `id`,
  MODIFY COLUMN `title` varchar(255) NULL COMMENT '标题(查询)' AFTER `name`,
  MODIFY COLUMN `scroll_img` text NULL COMMENT '轮播图' AFTER `title`,
  MODIFY COLUMN `img` varchar(255) NULL COMMENT '图片' AFTER `scroll_img`,
  MODIFY COLUMN `video` varchar(255) NULL COMMENT '视频' AFTER `img`,
  MODIFY COLUMN `detail` text NULL COMMENT '详情' AFTER `video`,
  MODIFY COLUMN `goods_type` int NULL COMMENT '商品类型' AFTER `detail`,
  MODIFY COLUMN `account_id` bigint NULL COMMENT '账号ID' AFTER `goods_type`,
  MODIFY COLUMN `category_id` bigint NULL COMMENT '所属平台分类' AFTER `account_id`,
  MODIFY COLUMN `category_name` varchar(255) NULL COMMENT '所属平台分类名称完整' AFTER `category_id`,
  MODIFY COLUMN `brand_id` bigint NULL COMMENT '品牌id' AFTER `category_name`,
  MODIFY COLUMN `brand_name` varchar(255) NULL COMMENT '品牌名称' AFTER `brand_id`,
  MODIFY COLUMN `freight_template_id` bigint NULL COMMENT '运费模板id' AFTER `brand_name`,
  MODIFY COLUMN `deliver_time_type` int NULL COMMENT '发货时效类型' AFTER `freight_template_id`,
  MODIFY COLUMN `max_deliver_day` int NULL COMMENT '最大发货天数' AFTER `deliver_time_type`,
  MODIFY COLUMN `state` int NULL COMMENT '状态' AFTER `max_deliver_day`,
  MODIFY COLUMN `code` varchar(255) NULL COMMENT '编码' AFTER `state`,
  MODIFY COLUMN `supplier_sale_amount` bigint NULL COMMENT '供应商销售金额' AFTER `code`,
  MODIFY COLUMN `account_name` varchar(255) NULL COMMENT '账号名称' AFTER `supplier_sale_amount`,
  MODIFY COLUMN `market_price` bigint NULL COMMENT '市场价' AFTER `account_name`,
  MODIFY COLUMN `supply_price` bigint NULL COMMENT '供货价' AFTER `market_price`,
  MODIFY COLUMN `sale_price` bigint NULL COMMENT '销售价' AFTER `supply_price`,
  MODIFY COLUMN `unit_price` bigint NULL COMMENT '销售价' AFTER `sale_price`,
  MODIFY COLUMN `sale_num` int NULL COMMENT '总销量' AFTER `unit_price`,
  MODIFY COLUMN `virtual_sale_num` int NULL COMMENT '虚拟销量' AFTER `sale_num`,
  MODIFY COLUMN `selection_num` int NULL COMMENT '选品数量' AFTER `virtual_sale_num`,
  MODIFY COLUMN `admin_sale_amount` bigint NULL COMMENT '平台销售额' AFTER `selection_num`,
  MODIFY COLUMN `channel_sale_amount` bigint NULL COMMENT '渠道商销售额' AFTER `admin_sale_amount`,
  MODIFY COLUMN `channel_type` int NULL COMMENT '渠道类型' AFTER `channel_sale_amount`,
  MODIFY COLUMN `out_spu_id` varchar(255) NULL COMMENT '外部供应链商品ID' AFTER `channel_type`,
  CHANGE COLUMN role_id `role` bigint NULL COMMENT '角色ID' AFTER `out_spu_id`,
  MODIFY COLUMN `max_profit` bigint NULL COMMENT '最大利润' AFTER `role`,
  MODIFY COLUMN `market_price_began` bigint NULL COMMENT '市场价起始' AFTER `max_profit`,
  MODIFY COLUMN `market_price_end` bigint NULL COMMENT '市场价结束' AFTER `market_price_began`,
  MODIFY COLUMN `sale_price_began` bigint NULL COMMENT '销售价起始' AFTER `market_price_end`,
  MODIFY COLUMN `sale_price_end` bigint NULL COMMENT '销售价结束' AFTER `sale_price_began`,
  MODIFY COLUMN `deal_num` int NULL COMMENT '成交数量',
  MODIFY COLUMN `refund_num` int NULL COMMENT '售后数量',
  MODIFY COLUMN `supplier_price_began` bigint NULL COMMENT '供货价起始' AFTER `refund_num`,
  MODIFY COLUMN `supplier_price_end` bigint NULL COMMENT '供货价结束' AFTER `supplier_price_began`,
  MODIFY COLUMN `audit_state` int NULL COMMENT '审批状态' AFTER `supplier_price_end`,
  MODIFY COLUMN `last_refuse_reason` varchar(255) NULL COMMENT '最后拒绝原因(状态变更至待用户提交前的最后一次拒绝原因)' AFTER `audit_state`,
  MODIFY COLUMN `flow_id` bigint NULL COMMENT '审批流ID' AFTER `last_refuse_reason`,
  MODIFY COLUMN `out_state` int NULL COMMENT '外部商品状态(0 已上架，1 已下架)' AFTER `flow_id`,
  MODIFY COLUMN `limit_area` varchar(255) NULL COMMENT '销售区域' AFTER `out_state`,
  MODIFY COLUMN `spec_type` int NULL COMMENT '规格类型' AFTER `limit_area`,
  MODIFY COLUMN `min_pricing_num` double(6, 2) NULL COMMENT '最小计价数' AFTER `spec_type`,
ADD
  COLUMN `supplier_id` bigint NULL COMMENT '供应商ID' AFTER `min_pricing_num`,
ADD
  COLUMN `executor` json NULL COMMENT '操作人信息' AFTER `supplier_id`,
ADD
  COLUMN `creator_id` bigint NULL COMMENT '创建人id' AFTER `executor`,
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
ADD
  COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
ADD
  INDEX `auto_idx_spu_name`(`name`) COMMENT '名称',
ADD
  INDEX `auto_idx_spu_account_id`(`account_id`) COMMENT '账号ID',
ADD
  INDEX `auto_idx_spu_category_id`(`category_id`) COMMENT '所属平台分类',
ADD
  INDEX `auto_idx_spu_brand_id`(`brand_id`) COMMENT '品牌id',
ADD
  INDEX `auto_idx_spu_freight_template_id`(`freight_template_id`) COMMENT '运费模板id',
ADD
  INDEX `auto_idx_spu_state`(`state`) COMMENT '状态',
ADD
  INDEX `auto_idx_spu_supplier_id`(`supplier_id`) COMMENT '供应商ID';
