ALTER TABLE
  `spu` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT 'name',
  MODIFY COLUMN `title` varchar(255) NULL COMMENT 'title',
  MODIFY COLUMN `scroll_img` text NULL COMMENT 'scrollImg',
  MODIFY COLUMN `search_key` varchar(255) NULL COMMENT 'searchKey',
  MODIFY COLUMN `img` varchar(255) NULL COMMENT 'img',
  MODIFY COLUMN `video` varchar(255) NULL COMMENT 'video',
  MODIFY COLUMN `detail` text NULL COMMENT 'detail',
  MODIFY COLUMN `account_id` bigint NULL COMMENT 'accountId',
  MODIFY COLUMN `category_id` bigint NULL COMMENT 'categoryId',
  MODIFY COLUMN `brand_id` bigint NULL COMMENT 'brandId',
  MODIFY COLUMN `freight_template_id` bigint NULL COMMENT 'freightTemplateId',
  MODIFY COLUMN `deliver_time_type` int NULL COMMENT 'deliverTimeType[03日内,1大于3日]',
  MODIFY COLUMN `max_deliver_day` int NULL COMMENT 'maxDeliverDay',
  MODIFY COLUMN `state` int NULL COMMENT 'state[-1初始化,0仓库中,1平台下架,2在售,3供应商下架]',
  MODIFY COLUMN `code` varchar(255) NULL COMMENT 'code',
  MODIFY COLUMN `market_price` bigint NULL COMMENT 'marketPrice',
  MODIFY COLUMN `supply_price` bigint NULL COMMENT 'supplyPrice',
  MODIFY COLUMN `sale_price` bigint NULL COMMENT 'salePrice',
  MODIFY COLUMN `unit_price` bigint NULL COMMENT 'unitPrice',
  MODIFY COLUMN `sale_num` int NULL COMMENT 'saleNum',
  MODIFY COLUMN `virtual_sale_num` int NULL COMMENT 'virtualSaleNum',
  MODIFY COLUMN `channel_type` int NULL COMMENT 'channelType[0供应商商品,2外部供应链商品]',
  MODIFY COLUMN `out_spu_id` varchar(255) NULL COMMENT 'outSpuId',
  MODIFY COLUMN `identity` int NULL COMMENT 'identity[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `audit_state` int NULL COMMENT 'auditState[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `last_refuse_reason` varchar(255) NULL COMMENT 'lastRefuseReason',
  MODIFY COLUMN `out_state` int NULL COMMENT 'outState',
  MODIFY COLUMN `expand` json NULL COMMENT 'expand',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'SpuDO表';
