ALTER TABLE
  `spu` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '名称(查询)',
  MODIFY COLUMN `title` varchar(255) NULL COMMENT '标题(查询)',
  MODIFY COLUMN `scroll_img` text NULL COMMENT '轮播图',
  MODIFY COLUMN `search_key` varchar(255) NULL COMMENT '搜索关键字(逗号隔开)',
  MODIFY COLUMN `img` varchar(255) NULL COMMENT '图片',
  MODIFY COLUMN `video` varchar(255) NULL COMMENT '视频',
  MODIFY COLUMN `detail` text NULL COMMENT '详情',
  MODIFY COLUMN `account_id` bigint NULL COMMENT '账号ID',
  MODIFY COLUMN `category_id` bigint NULL COMMENT '所属平台分类',
  MODIFY COLUMN `brand_id` bigint NULL COMMENT '品牌id',
  MODIFY COLUMN `freight_template_id` bigint NULL COMMENT '运费模板id',
  MODIFY COLUMN `deliver_time_type` int NULL COMMENT '发货时效类型[03日内,1大于3日]',
  MODIFY COLUMN `max_deliver_day` int NULL COMMENT '最大发货天数',
  MODIFY COLUMN `state` int NULL COMMENT '状态[-1初始化,0仓库中,1平台下架,2在售,3供应商下架]',
  MODIFY COLUMN `code` varchar(255) NULL COMMENT '编码',
  MODIFY COLUMN `market_price` bigint NULL COMMENT '市场价',
  MODIFY COLUMN `supply_price` bigint NULL COMMENT '供货价',
  MODIFY COLUMN `sale_price` bigint NULL COMMENT '销售价',
  MODIFY COLUMN `unit_price` bigint NULL COMMENT '销售价',
  MODIFY COLUMN `sale_num` int NULL COMMENT '总销量',
  MODIFY COLUMN `virtual_sale_num` int NULL COMMENT '虚拟销量',
  MODIFY COLUMN `channel_type` int NULL COMMENT '渠道类型[0供应商商品,2外部供应链商品]',
  MODIFY COLUMN `out_spu_id` varchar(255) NULL COMMENT '外部供应链商品ID',
  MODIFY COLUMN `identity` int NULL COMMENT '角色ID[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `audit_state` int NULL COMMENT '审批状态[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `last_refuse_reason` varchar(255) NULL COMMENT '最后拒绝原因(状态变更至待用户提交前的最后一次拒绝原因)',
  MODIFY COLUMN `out_state` int NULL COMMENT '外部商品状态(0 已上架，1 已下架)',
  MODIFY COLUMN `expand` json NULL COMMENT '扩展字段(JSON 列, 对象直传, 存分类/品牌/账号名称与价格区间)',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = 'spu';
