CREATE TABLE `audit_data_spu` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `img` varchar(255) NULL COMMENT '商品URL',
  `name` varchar(255) NULL COMMENT '商品名称',
  `category_id` bigint NULL COMMENT '商品分类',
  `category_name` varchar(255) NULL COMMENT '商品分类名称完整',
  `spu_create_info_json` json NULL COMMENT '商品创建信息',
  `sku_sale_price_json` json NULL COMMENT 'sku销售价',
  `admin_user_name` varchar(255) NULL COMMENT 'sku审批人值对象',
  `brand_name` varchar(255) NULL COMMENT '品牌名称',
  `supply_price` bigint NULL COMMENT '供货价',
  `market_price` bigint NULL COMMENT '市场价',
  `unit_price` bigint NULL COMMENT '建议零售价',
  `state` int NULL COMMENT '审批状态',
  `foreign_id` bigint NULL COMMENT '外键id',
  `flow_id` bigint NULL COMMENT '审批流id',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_audit_data_spu_category_id`(`category_id`) COMMENT '商品分类',
  INDEX `auto_idx_audit_data_spu_flow_id`(`flow_id`) COMMENT '审批流id',
  INDEX `auto_idx_audit_data_spu_foreign_id`(`foreign_id`) COMMENT '外键id'
);
