CREATE TABLE `audit_data_work_table` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `spu_name` varchar(255) NULL COMMENT '商品名称(查询)',
  `operate_type` int NULL COMMENT '操作类型',
  `operate_target` int NULL COMMENT '操作目标',
  `spu_info_json` json NULL COMMENT '原商品信息',
  `spu_edit_info_json` json NULL COMMENT '商品修改信息',
  `sku_sale_price_json` json NULL COMMENT 'sku销售价',
  `state` int NULL COMMENT '审批状态',
  `foreign_id` bigint NULL COMMENT '外键id',
  `flow_id` bigint NULL COMMENT '审批流id',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_audit_data_work_table_flow_id`(`flow_id`) COMMENT '审批流id',
  INDEX `auto_idx_audit_data_work_table_foreign_id`(`foreign_id`) COMMENT '外键id',
  INDEX `auto_idx_audit_data_work_table_operate_target`(`operate_target`) COMMENT '操作目标'
);
