ALTER TABLE
  `supplier` DROP COLUMN `invite_id`,
  DROP COLUMN `role_id`,
  DROP COLUMN `role_name`,
  DROP COLUMN `username`,
  DROP COLUMN `deposit`,
  DROP COLUMN `max_sku_num`,
  DROP COLUMN `goods_total_count`,
  DROP COLUMN `goods_on_sale_count`,
  DROP COLUMN `goods_sale_amount`,
  DROP COLUMN `goods_sale_count`,
  DROP COLUMN `goods_deal_count`,
  DROP COLUMN `goods_not_sale_count`,
  DROP COLUMN `service_fee_config_v_o`,
  DROP COLUMN `total_order_number`,
  DROP COLUMN `total_refund_number`,
  DROP COLUMN `total_order_amount`,
  DROP COLUMN `total_refund_amount`,
  DROP COLUMN `month_goods_sale_amount`,
  DROP COLUMN `month_goods_sale_count`,
  MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `audit_state` int NULL COMMENT '审批状态' AFTER `id`,
  MODIFY COLUMN `state` int NULL COMMENT '状态' AFTER `audit_state`,
  MODIFY COLUMN `company_area_code` varchar(255) NULL COMMENT '企业区域编码' AFTER `state`,
  MODIFY COLUMN `company_info` json NULL COMMENT '企业信息' AFTER `company_area_code`,
  MODIFY COLUMN `promise_pay_state` int NULL COMMENT '是否缴纳保证金' AFTER `company_info`,
  MODIFY COLUMN `promise_pay_amount` bigint NULL COMMENT '保证金金额(Money, 落库 BIGINT 分)' AFTER `promise_pay_state`,
  MODIFY COLUMN `promise_pay_audit_state` int NULL COMMENT '保证金审批状态' AFTER `promise_pay_amount`,
  MODIFY COLUMN `promise_pay_config` int NULL COMMENT '保证金缴纳配置(源列 promise_pay_config; 0 即时, 1 延迟)' AFTER `promise_pay_audit_state`,
  MODIFY COLUMN `period_set_state` int NULL COMMENT '是否设置账期' AFTER `promise_pay_config`,
  MODIFY COLUMN `period_set_config` varchar(255) NULL COMMENT '账期配置JSON' AFTER `period_set_state`,
  MODIFY COLUMN `should_promise_pay_amount` bigint NULL COMMENT '应付保证金金额(Money, 落库 BIGINT 分)' AFTER `period_set_config`,
  MODIFY COLUMN `body_type` int NULL COMMENT '主体类型' AFTER `should_promise_pay_amount`,
  MODIFY COLUMN `audit_refuse_reason` varchar(255) NULL COMMENT '审批拒绝原因' AFTER `body_type`,
  MODIFY COLUMN `industry_id_list` varchar(255) NULL COMMENT '行业ID集合',
ADD
  COLUMN `settlement_config_v_o` varchar(255) NULL COMMENT '结算配置' AFTER `industry_id_list`,
  MODIFY COLUMN `receive_address` varchar(255) NULL COMMENT '收货地址' AFTER `settlement_config_v_o`,
  MODIFY COLUMN `in_time` datetime NULL COMMENT '入驻时间' AFTER `receive_address`,
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '名称(冗余字段)',
ADD
  COLUMN `executor` json NULL COMMENT '操作人信息' AFTER `name`,
ADD
  COLUMN `creator_id` bigint NULL COMMENT '创建人id' AFTER `executor`,
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
ADD
  COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
