ALTER TABLE
  `supplier` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `audit_state` int NULL COMMENT '审批状态[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `state` int NULL COMMENT '状态[0未开通,1审核申请中,2已入驻]',
  MODIFY COLUMN `company_area_code` varchar(255) NULL COMMENT '企业区域编码',
  MODIFY COLUMN `company_info` json NULL COMMENT '企业信息',
  MODIFY COLUMN `promise_pay_state` int NULL COMMENT '是否缴纳保证金[1是,0否]',
  MODIFY COLUMN `promise_pay_amount` bigint NULL COMMENT '保证金金额(Money, 落库 BIGINT 分)',
  MODIFY COLUMN `promise_pay_audit_state` int NULL COMMENT '保证金审批状态[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `promise_pay_config` int NULL COMMENT '保证金缴纳配置(源列 promise_pay_config; 0 即时, 1 延迟)',
  MODIFY COLUMN `period_set_state` int NULL COMMENT '是否设置账期[1是,0否]',
  MODIFY COLUMN `period_set_config` json NULL COMMENT '账期配置JSON',
  MODIFY COLUMN `should_promise_pay_amount` bigint NULL COMMENT '应付保证金金额(Money, 落库 BIGINT 分)',
  MODIFY COLUMN `audit_refuse_reason` varchar(255) NULL COMMENT '审批拒绝原因',
  MODIFY COLUMN `industry_id_list` varchar(255) NULL COMMENT '行业ID集合',
  MODIFY COLUMN `settlement_config_v_o` varchar(255) NULL COMMENT '结算配置',
  MODIFY COLUMN `receive_address` varchar(255) NULL COMMENT '收货地址',
  MODIFY COLUMN `in_time` datetime NULL COMMENT '入驻时间',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '名称(冗余字段)',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '供应商';
