ALTER TABLE
  `supplier` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `audit_state` int NULL COMMENT 'auditState[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `state` int NULL COMMENT 'state[0未开通,1审核申请中,2已入驻]',
  MODIFY COLUMN `company_area_code` varchar(255) NULL COMMENT 'companyAreaCode',
  MODIFY COLUMN `company_info` json NULL COMMENT 'companyInfo',
  MODIFY COLUMN `promise_pay_state` int NULL COMMENT 'promisePayState[1是,0否]',
  MODIFY COLUMN `promise_pay_amount` bigint NULL COMMENT 'promisePayAmount',
  MODIFY COLUMN `promise_pay_audit_state` int NULL COMMENT 'promisePayAuditState[0待用户提交,1待审核,2通过,3未通过,4终止]',
  MODIFY COLUMN `promise_pay_config` int NULL COMMENT 'promisePayConfig',
  MODIFY COLUMN `period_set_state` int NULL COMMENT 'periodSetState[1是,0否]',
  MODIFY COLUMN `period_set_config` json NULL COMMENT 'periodSetConfig',
  MODIFY COLUMN `should_promise_pay_amount` bigint NULL COMMENT 'shouldPromisePayAmount',
  MODIFY COLUMN `audit_refuse_reason` varchar(255) NULL COMMENT 'auditRefuseReason',
  MODIFY COLUMN `industry_id_list` varchar(255) NULL COMMENT 'industryIdList',
  MODIFY COLUMN `settlement_config_v_o` varchar(255) NULL COMMENT 'settlementConfigVO',
  MODIFY COLUMN `receive_address` varchar(255) NULL COMMENT 'receiveAddress',
  MODIFY COLUMN `in_time` datetime NULL COMMENT 'inTime',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT 'name',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'SupplierDO表';
