CREATE TABLE `supplier` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `audit_state` int NULL COMMENT '审批状态',
  `state` int NULL COMMENT '状态',
  `company_area_code` varchar(255) NULL COMMENT '企业区域编码',
  `company_info` json NULL COMMENT '企业信息',
  `promise_pay_state` int NULL COMMENT '是否缴纳保证金',
  `promise_pay_amount` bigint NULL COMMENT '保证金金额(Money, 落库 BIGINT 分)',
  `promise_pay_audit_state` int NULL COMMENT '保证金审批状态',
  `promise_pay_config` int NULL COMMENT '保证金缴纳配置(源列 promise_pay_config; 0 即时, 1 延迟)',
  `period_set_state` int NULL COMMENT '是否设置账期',
  `period_set_config` varchar(255) NULL COMMENT '账期配置JSON',
  `should_promise_pay_amount` bigint NULL COMMENT '应付保证金金额(Money, 落库 BIGINT 分)',
  `audit_refuse_reason` varchar(255) NULL COMMENT '审批拒绝原因',
  `industry_id_list` varchar(255) NULL COMMENT '行业ID集合',
  `settlement_config_v_o` varchar(255) NULL COMMENT '结算配置',
  `receive_address` varchar(255) NULL COMMENT '收货地址',
  `in_time` datetime NULL COMMENT '入驻时间',
  `name` varchar(255) NULL COMMENT '名称(冗余字段)',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`)
) COMMENT = '供应商';
