ALTER TABLE
  `sku` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `code` varchar(255) NULL COMMENT 'code',
  MODIFY COLUMN `img` varchar(255) NULL COMMENT 'img',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT 'name',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'spuId',
  MODIFY COLUMN `market_price` bigint NULL COMMENT 'marketPrice',
  MODIFY COLUMN `supply_price` bigint NULL COMMENT 'supplyPrice',
  MODIFY COLUMN `sale_price` bigint NULL COMMENT 'salePrice',
  MODIFY COLUMN `unit_price` bigint NULL COMMENT 'unitPrice',
  MODIFY COLUMN `sale_attribute` json NULL COMMENT 'saleAttribute',
  MODIFY COLUMN `out_sku_id` varchar(255) NULL COMMENT 'outSkuId',
  MODIFY COLUMN `sale_price_rate` float(4, 2) NULL COMMENT 'salePriceRate',
  MODIFY COLUMN `buy_start_qty` int NULL COMMENT 'buyStartQty',
  MODIFY COLUMN `expand` json NULL COMMENT 'expand',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'SkuDO表';
