ALTER TABLE
  `sku` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `code` varchar(255) NULL COMMENT '编码',
  MODIFY COLUMN `img` varchar(255) NULL COMMENT '图片',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '名称',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'spuId(查询)',
  MODIFY COLUMN `market_price` bigint NULL COMMENT '市场价',
  MODIFY COLUMN `supply_price` bigint NULL COMMENT '供货价',
  MODIFY COLUMN `sale_price` bigint NULL COMMENT '销售价(to channel)',
  MODIFY COLUMN `unit_price` bigint NULL COMMENT '销售价(to c)',
  MODIFY COLUMN `sale_attribute` json NULL COMMENT '商品销售属性(JSON 列, 对象直传)',
  MODIFY COLUMN `out_sku_id` varchar(255) NULL COMMENT '外部SkuId',
  MODIFY COLUMN `sale_price_rate` float(4, 2) NULL COMMENT '销售价加价比例',
  MODIFY COLUMN `buy_start_qty` int NULL COMMENT '起购数量',
  MODIFY COLUMN `expand` json NULL COMMENT '追加: 扩展字段(JSON 列, 对象直传)',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = 'sku';
