CREATE TABLE `user_collection` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `user_id` bigint NULL COMMENT '用户ID',
  `user_name` varchar(255) NULL COMMENT '用户名称',
  `store_id` bigint NULL COMMENT '门店ID',
  `store_name` varchar(255) NULL COMMENT '门店名称',
  `store_distribution_id` bigint NULL COMMENT '铺货表ID',
  `spu_id` bigint NULL COMMENT 'SPU ID',
  `spu_name` varchar(255) NULL COMMENT 'SPU 名称(快照)',
  `sku_id` bigint NULL COMMENT 'SKU ID',
  `sku_name` varchar(255) NULL COMMENT 'SKU 名称(快照)',
  `price` bigint NULL COMMENT '商品价格(快照)',
  `main_image` varchar(255) NULL COMMENT '商品主图URL(快照)',
  `is_valid` int NULL COMMENT '是否有效',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_user_collection_sku_id`(`sku_id`) COMMENT 'SKU ID',
  INDEX `auto_idx_user_collection_spu_id`(`spu_id`) COMMENT 'SPU ID',
  INDEX `auto_idx_user_collection_store_distribution_id`(`store_distribution_id`) COMMENT '铺货表ID',
  INDEX `auto_idx_user_collection_store_id`(`store_id`) COMMENT '门店ID',
  INDEX `auto_idx_user_collection_user_id`(`user_id`) COMMENT '用户ID'
) COMMENT = '用户商品收藏持久化对象';
