ALTER TABLE
  `user_collection` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `user_id` bigint NULL COMMENT 'userId',
  MODIFY COLUMN `user_name` varchar(255) NULL COMMENT 'userName',
  MODIFY COLUMN `store_id` bigint NULL COMMENT 'storeId',
  MODIFY COLUMN `store_name` varchar(255) NULL COMMENT 'storeName',
  MODIFY COLUMN `store_distribution_id` bigint NULL COMMENT 'storeDistributionId',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'spuId',
  MODIFY COLUMN `spu_name` varchar(255) NULL COMMENT 'spuName',
  MODIFY COLUMN `sku_id` bigint NULL COMMENT 'skuId',
  MODIFY COLUMN `sku_name` varchar(255) NULL COMMENT 'skuName',
  MODIFY COLUMN `price` bigint NULL COMMENT 'price',
  MODIFY COLUMN `main_image` varchar(255) NULL COMMENT 'mainImage',
  MODIFY COLUMN `is_valid` int NULL COMMENT 'isValid[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'UserCollectionDO表';
