ALTER TABLE
  `user_collection` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `user_id` bigint NULL COMMENT '用户ID',
  MODIFY COLUMN `user_name` varchar(255) NULL COMMENT '用户名称',
  MODIFY COLUMN `store_id` bigint NULL COMMENT '门店ID',
  MODIFY COLUMN `store_name` varchar(255) NULL COMMENT '门店名称',
  MODIFY COLUMN `store_distribution_id` bigint NULL COMMENT '铺货表ID',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'SPU ID',
  MODIFY COLUMN `spu_name` varchar(255) NULL COMMENT 'SPU 名称(快照)',
  MODIFY COLUMN `sku_id` bigint NULL COMMENT 'SKU ID',
  MODIFY COLUMN `sku_name` varchar(255) NULL COMMENT 'SKU 名称(快照)',
  MODIFY COLUMN `price` bigint NULL COMMENT '商品价格(快照)',
  MODIFY COLUMN `main_image` varchar(255) NULL COMMENT '商品主图URL(快照)',
  MODIFY COLUMN `is_valid` int NULL COMMENT '是否有效[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '用户商品收藏持久化对象';
