CREATE TABLE `user_interaction` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `user_id` bigint NULL COMMENT '操作人ID(关联用户表)',
  `publisher_id` bigint NULL COMMENT '被操作对象发布者ID(视频/商品的发布者，关联用户表)',
  `store_id` bigint NULL COMMENT '门店ID',
  `target_type` varchar(255) NULL COMMENT '被操作对象类型',
  `target_id` bigint NULL COMMENT '被操作对象ID(视频ID或商品ID，与targetType对应)',
  `action_type` varchar(255) NULL COMMENT '操作类型',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_user_interaction_publisher_id`(`publisher_id`) COMMENT '被操作对象发布者ID',
  INDEX `auto_idx_user_interaction_store_id`(`store_id`) COMMENT '门店ID',
  INDEX `auto_idx_user_interaction_target_id`(`target_id`) COMMENT '被操作对象ID',
  INDEX `auto_idx_user_interaction_target_type`(`target_type`) COMMENT '被操作对象类型',
  INDEX `auto_idx_user_interaction_user_id`(`user_id`) COMMENT '操作人ID'
) COMMENT = '用户互动操作持久化对象（存储点赞、转发记录）';
