ALTER TABLE
  `local_message` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `topic` varchar(50) NOT NULL COMMENT 'topic',
  MODIFY COLUMN `tag` varchar(255) NOT NULL COMMENT 'tag',
  MODIFY COLUMN `out_key` varchar(255) NULL COMMENT 'outKey',
  MODIFY COLUMN `send_state` int NOT NULL COMMENT 'sendState[0待发送,1发送中,2发送成功,3发送失败]',
  MODIFY COLUMN `message_content` json NOT NULL COMMENT 'messageContent',
  MODIFY COLUMN `message_class` varchar(255) NOT NULL COMMENT 'messageClass',
  MODIFY COLUMN `message_id` varchar(50) NULL COMMENT 'messageId',
  MODIFY COLUMN `consume_state` int NOT NULL COMMENT 'consumeState[0待消费,1消费成功,2消费失败,3异常:需人工处理]',
  MODIFY COLUMN `can_consume` int NOT NULL COMMENT 'canConsume[1是,0否]',
  MODIFY COLUMN `send_count` int NOT NULL COMMENT 'sendCount',
  MODIFY COLUMN `send_time` datetime NULL COMMENT 'sendTime',
  MODIFY COLUMN `consume_time` datetime NULL COMMENT 'consumeTime',
  MODIFY COLUMN `consume_error_msg` text NULL COMMENT 'consumeErrorMsg',
  MODIFY COLUMN `consume_error_count` int NOT NULL COMMENT 'consumeErrorCount',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'LocalMessageDO表';
