CREATE TABLE `local_message` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `topic` varchar(50) NOT NULL COMMENT '消息主题',
  `tag` varchar(255) NOT NULL COMMENT '消息标签',
  `out_key` varchar(255) NULL COMMENT '外部唯一键(用于延迟消息唤醒)',
  `send_state` int NOT NULL COMMENT '发送状态',
  `message_content` json NOT NULL COMMENT '消息体',
  `message_class` varchar(255) NOT NULL COMMENT '消息体类全路径',
  `message_id` varchar(50) NULL COMMENT 'RocketMQ 消息 ID',
  `consume_state` int NOT NULL COMMENT '消费状态(0-待消费, 1-消费成功, 2-消费失败, 3-异常)',
  `can_consume` int NOT NULL COMMENT '可消费标识(0-不可消费, 1-可消费)',
  `send_count` int NOT NULL COMMENT '发送次数',
  `send_time` datetime NULL COMMENT '发送时间',
  `consume_time` datetime NULL COMMENT '消费时间',
  `consume_error_msg` text NULL COMMENT '消费异常信息',
  `consume_error_count` int NOT NULL COMMENT '消费异常次数',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_local_message_consume_state`(`consume_state`) COMMENT '消费状态',
  INDEX `auto_idx_local_message_consume_time`(`consume_time`) COMMENT '消费时间',
  INDEX `auto_idx_local_message_send_state`(`send_state`) COMMENT '发送状态',
  INDEX `auto_idx_local_message_tag`(`tag`) COMMENT '消息标签',
  INDEX `auto_idx_local_message_topic`(`topic`) COMMENT '消息主题'
) COMMENT = '本地消息实体';
