ALTER TABLE
  `local_message` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `topic` varchar(50) NOT NULL COMMENT '消息主题',
  MODIFY COLUMN `tag` varchar(255) NOT NULL COMMENT '消息标签',
  MODIFY COLUMN `out_key` varchar(255) NULL COMMENT '外部唯一键(用于延迟消息唤醒)',
  MODIFY COLUMN `send_state` int NOT NULL COMMENT '发送状态[0待发送,1发送中,2发送成功,3发送失败]',
  MODIFY COLUMN `message_content` json NOT NULL COMMENT '消息体',
  MODIFY COLUMN `message_class` varchar(255) NOT NULL COMMENT '消息体类全路径',
  MODIFY COLUMN `message_id` varchar(50) NULL COMMENT 'RocketMQ 消息 ID',
  MODIFY COLUMN `consume_state` int NOT NULL COMMENT '消费状态(0-待消费, 1-消费成功, 2-消费失败, 3-异常)[0待消费,1消费成功,2消费失败,3异常:需人工处理]',
  MODIFY COLUMN `can_consume` int NOT NULL COMMENT '可消费标识(0-不可消费, 1-可消费)[1是,0否]',
  MODIFY COLUMN `send_count` int NOT NULL COMMENT '发送次数',
  MODIFY COLUMN `send_time` datetime NULL COMMENT '发送时间',
  MODIFY COLUMN `consume_time` datetime NULL COMMENT '消费时间',
  MODIFY COLUMN `consume_error_msg` text NULL COMMENT '消费异常信息',
  MODIFY COLUMN `consume_error_count` int NOT NULL COMMENT '消费异常次数',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '本地消息实体';
