CREATE TABLE `store_style` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `style_code` varchar(255) NULL COMMENT '样式code',
  `style_name` varchar(255) NULL COMMENT '样式名称',
  `essential_colour` varchar(255) NULL COMMENT '主色',
  `auxiliary_color` varchar(255) NULL COMMENT '辅色',
  `use_store_num` int NULL COMMENT '使用门店数',
  `package_describe` varchar(255) NULL COMMENT '描述',
  `type` int NULL COMMENT '类型：1 默认',
  `state` int NULL COMMENT '状态：0 禁用,1 启用',
  `source_code` varchar(255) NULL COMMENT '来源模板code',
  `source_name` varchar(255) NULL COMMENT '来源模板名称',
  `page_type` varchar(255) NULL COMMENT '页面类型',
  `style_content` text NULL COMMENT '样式内容',
  `goods_id_list_str` varchar(255) NULL COMMENT '商品id集合',
  `preview_image` varchar(255) NULL COMMENT '预览图',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_store_style_essential_colour`(`essential_colour`) COMMENT '主色',
  INDEX `auto_idx_store_style_source_code`(`source_code`) COMMENT '来源模板code',
  INDEX `auto_idx_store_style_style_code`(`style_code`) COMMENT '样式code'
) COMMENT = '门店样式领域对象';
