ALTER TABLE
  `store_style` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `style_code` varchar(255) NULL COMMENT 'styleCode',
  MODIFY COLUMN `style_name` varchar(255) NULL COMMENT 'styleName',
  MODIFY COLUMN `essential_colour` varchar(255) NULL COMMENT 'essentialColour',
  MODIFY COLUMN `auxiliary_color` varchar(255) NULL COMMENT 'auxiliaryColor',
  MODIFY COLUMN `use_store_num` int NULL COMMENT 'useStoreNum',
  MODIFY COLUMN `package_describe` varchar(255) NULL COMMENT 'packageDescribe',
  MODIFY COLUMN `type` int NULL COMMENT 'type',
  MODIFY COLUMN `state` int NULL COMMENT 'state',
  MODIFY COLUMN `source_code` varchar(255) NULL COMMENT 'sourceCode',
  MODIFY COLUMN `source_name` varchar(255) NULL COMMENT 'sourceName',
  MODIFY COLUMN `page_type` varchar(255) NULL COMMENT 'pageType',
  MODIFY COLUMN `style_content` text NULL COMMENT 'styleContent',
  MODIFY COLUMN `goods_id_list_str` varchar(255) NULL COMMENT 'goodsIdListStr',
  MODIFY COLUMN `preview_image` varchar(255) NULL COMMENT 'previewImage',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'StoreStyleDO表';
