ALTER TABLE
  `store` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT 'name',
  MODIFY COLUMN `logo` varchar(255) NULL COMMENT 'logo',
  MODIFY COLUMN `address` varchar(255) NULL COMMENT 'address',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT 'channelId',
  MODIFY COLUMN `model_shop_id` bigint NULL COMMENT 'modelShopId',
  MODIFY COLUMN `is_model_shop` int NULL COMMENT 'isModelShop',
  MODIFY COLUMN `style_code` varchar(255) NULL COMMENT 'styleCode',
  MODIFY COLUMN `category_id` bigint NULL COMMENT 'categoryId',
  MODIFY COLUMN `category_name` varchar(255) NULL COMMENT 'categoryName',
  MODIFY COLUMN `style_content` varchar(255) NULL COMMENT 'styleContent',
  MODIFY COLUMN `goods_id_list_str` varchar(255) NULL COMMENT 'goodsIdListStr',
  MODIFY COLUMN `preview_image` varchar(255) NULL COMMENT 'previewImage',
  MODIFY COLUMN `style_name` varchar(255) NULL COMMENT 'styleName',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'StoreDO表';
