CREATE TABLE `store_account` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `store_id` bigint NULL COMMENT '门店id',
  `account_id` bigint NULL COMMENT '客户id',
  `channel_id` bigint NULL COMMENT '渠道商ID',
  `last_view_time` datetime NULL COMMENT '最后进店时间',
  `last_pay_time` datetime NULL COMMENT '最后支付时间',
  `last_pay_amount` bigint NULL COMMENT '最后支付金额',
  `relation_type` int NULL COMMENT '0:未拉黑，1已拉黑',
  `defult` int NULL COMMENT '是否默认：1 是',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_store_account_account_id`(`account_id`) COMMENT '客户id',
  INDEX `auto_idx_store_account_channel_id`(`channel_id`) COMMENT '渠道商ID',
  INDEX `auto_idx_store_account_store_id`(`store_id`) COMMENT '门店id'
) COMMENT = '门店客户表';
