ALTER TABLE
  `store_account` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `store_id` bigint NULL COMMENT '门店id',
  MODIFY COLUMN `account_id` bigint NULL COMMENT '客户id',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT '渠道商ID',
  MODIFY COLUMN `last_view_time` datetime NULL COMMENT '最后进店时间',
  MODIFY COLUMN `last_pay_time` datetime NULL COMMENT '最后支付时间',
  MODIFY COLUMN `last_pay_amount` bigint NULL COMMENT '最后支付金额',
  MODIFY COLUMN `relation_type` int NULL COMMENT '0:未拉黑，1已拉黑',
  MODIFY COLUMN `defult` int NULL COMMENT '是否默认：1 是[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '门店客户表';
