ALTER TABLE
  `store` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `name` varchar(255) NULL COMMENT '门店名称',
  MODIFY COLUMN `logo` varchar(255) NULL COMMENT '门店logo',
  MODIFY COLUMN `address` varchar(255) NULL COMMENT '地址',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT '渠道商ID',
  MODIFY COLUMN `model_shop_id` bigint NULL COMMENT '样板店ID',
  MODIFY COLUMN `is_model_shop` int NULL COMMENT '是否是样板店',
  MODIFY COLUMN `style_code` varchar(255) NULL COMMENT '样式code',
  MODIFY COLUMN `category_id` bigint NULL COMMENT '门店类型',
  MODIFY COLUMN `category_name` varchar(255) NULL COMMENT '门店类型名称',
  MODIFY COLUMN `style_content` varchar(255) NULL COMMENT '样式内容',
  MODIFY COLUMN `goods_id_list_str` varchar(255) NULL COMMENT '商品id集合',
  MODIFY COLUMN `preview_image` varchar(255) NULL COMMENT '预览图',
  MODIFY COLUMN `style_name` varchar(255) NULL COMMENT '样式名称',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '门店';
