CREATE TABLE `store` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `name` varchar(255) NULL COMMENT '门店名称',
  `logo` varchar(255) NULL COMMENT '门店logo',
  `address` varchar(255) NULL COMMENT '地址',
  `channel_id` bigint NULL COMMENT '渠道商ID',
  `model_shop_id` bigint NULL COMMENT '样板店ID',
  `is_model_shop` int NULL COMMENT '是否是样板店',
  `style_code` varchar(255) NULL COMMENT '样式code',
  `category_id` bigint NULL COMMENT '门店类型',
  `category_name` varchar(255) NULL COMMENT '门店类型名称',
  `style_content` varchar(255) NULL COMMENT '样式内容',
  `goods_id_list_str` varchar(255) NULL COMMENT '商品id集合',
  `preview_image` varchar(255) NULL COMMENT '预览图',
  `style_name` varchar(255) NULL COMMENT '样式名称',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_store_channel_id`(`channel_id`) COMMENT '渠道商ID',
  INDEX `auto_idx_store_model_shop_id`(`model_shop_id`) COMMENT '样板店ID',
  INDEX `auto_idx_store_name`(`name`) COMMENT '门店名称',
  INDEX `auto_idx_store_style_code`(`style_code`) COMMENT '样式code'
) COMMENT = '门店';
