ALTER TABLE
  `settle_order_wait` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT '供应商ID',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'SPU_订单ID',
  MODIFY COLUMN `sku_order_id` bigint NULL COMMENT 'sku订单ID',
  MODIFY COLUMN `type` int NULL COMMENT '类型(0 商品 1 运费 2 售后)',
  MODIFY COLUMN `order_money` bigint NULL COMMENT '订单结算金额',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'SPU_ID',
  MODIFY COLUMN `sku_id` bigint NULL COMMENT 'SKU_ID',
  MODIFY COLUMN `sku_count` int NULL COMMENT 'sku数量',
  MODIFY COLUMN `settle_state` int NULL COMMENT '结算状态[1是,0否]',
  MODIFY COLUMN `settle_time` datetime NULL COMMENT '结算时间',
  MODIFY COLUMN `refund_id` bigint NULL COMMENT '售后单ID',
  MODIFY COLUMN `refund_state` int NULL COMMENT '售后状态(对齐源 refund_state 列语义, 迁移补映射)',
  MODIFY COLUMN `settle_record_id` bigint NULL COMMENT '结算单ID',
  MODIFY COLUMN `refund_amount` bigint NULL COMMENT '售后金额 默认0',
  MODIFY COLUMN `settle_time_node` bigint NULL COMMENT '结算时间节点(时间戳)',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '待结算订单信息表';
