ALTER TABLE
  `settle_goods` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT '供应商ID',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'SPU_ID',
  MODIFY COLUMN `next_settle_time` datetime NULL COMMENT '下次结算时间',
  MODIFY COLUMN `settle_num` int NULL COMMENT '结算次数',
  MODIFY COLUMN `settle_money` bigint NULL COMMENT '结算金额',
  MODIFY COLUMN `settle_goods_num` int NULL COMMENT '结算商品数量',
  MODIFY COLUMN `up_num` int NULL COMMENT '账期修改次数',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '结算商品信息表';
