ALTER TABLE
  `settle_order_wait` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT 'supplierId',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'spuOrderId',
  MODIFY COLUMN `sku_order_id` bigint NULL COMMENT 'skuOrderId',
  MODIFY COLUMN `type` int NULL COMMENT 'type',
  MODIFY COLUMN `order_money` bigint NULL COMMENT 'orderMoney',
  MODIFY COLUMN `spu_id` bigint NULL COMMENT 'spuId',
  MODIFY COLUMN `sku_id` bigint NULL COMMENT 'skuId',
  MODIFY COLUMN `sku_count` int NULL COMMENT 'skuCount',
  MODIFY COLUMN `settle_state` int NULL COMMENT 'settleState[1是,0否]',
  MODIFY COLUMN `settle_time` datetime NULL COMMENT 'settleTime',
  MODIFY COLUMN `refund_id` bigint NULL COMMENT 'refundId',
  MODIFY COLUMN `refund_state` int NULL COMMENT 'refundState',
  MODIFY COLUMN `settle_record_id` bigint NULL COMMENT 'settleRecordId',
  MODIFY COLUMN `refund_amount` bigint NULL COMMENT 'refundAmount',
  MODIFY COLUMN `settle_time_node` bigint NULL COMMENT 'settleTimeNode',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'SettleOrderWaitDO表';
