CREATE TABLE `settle_order_wait` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `supplier_id` bigint NULL COMMENT '供应商ID',
  `spu_order_id` bigint NULL COMMENT 'SPU_订单ID',
  `sku_order_id` bigint NULL COMMENT 'sku订单ID',
  `type` int NULL COMMENT '类型(0 商品 1 运费 2 售后)',
  `order_money` bigint NULL COMMENT '订单结算金额',
  `spu_id` bigint NULL COMMENT 'SPU_ID',
  `sku_id` bigint NULL COMMENT 'SKU_ID',
  `sku_count` int NULL COMMENT 'sku数量',
  `settle_state` int NULL COMMENT '结算状态',
  `settle_time` datetime NULL COMMENT '结算时间',
  `refund_id` bigint NULL COMMENT '售后单ID',
  `refund_state` int NULL COMMENT '售后状态(对齐源 refund_state 列语义, 迁移补映射)',
  `settle_record_id` bigint NULL COMMENT '结算单ID',
  `refund_amount` bigint NULL COMMENT '售后金额 默认0',
  `settle_time_node` bigint NULL COMMENT '结算时间节点(时间戳)',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`),
  INDEX `auto_idx_settle_order_wait_refund_id`(`refund_id`) COMMENT '售后单ID',
  INDEX `auto_idx_settle_order_wait_settle_record_id`(`settle_record_id`) COMMENT '结算单ID',
  INDEX `auto_idx_settle_order_wait_sku_id`(`sku_id`) COMMENT 'SKU_ID',
  INDEX `auto_idx_settle_order_wait_sku_order_id`(`sku_order_id`) COMMENT 'sku订单ID',
  INDEX `auto_idx_settle_order_wait_spu_id`(`spu_id`) COMMENT 'SPU_ID',
  INDEX `auto_idx_settle_order_wait_spu_order_id`(`spu_order_id`) COMMENT 'SPU_订单ID',
  INDEX `auto_idx_settle_order_wait_supplier_id`(`supplier_id`) COMMENT '供应商ID'
) COMMENT = '待结算订单信息表';
