CREATE TABLE `refund_operation_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `spu_order_id` bigint NULL COMMENT 'spu订单id',
  `refund_id` bigint NULL COMMENT '售后单refund表的主键',
  `operator_id` bigint NULL COMMENT '操作人ID',
  `operator_role_code` bigint NULL COMMENT '操作方角色编码',
  `operator_client` varchar(255) NULL COMMENT '操作方客户端类型',
  `operator_name` varchar(255) NULL COMMENT '操作方名称',
  `before_state` int NULL COMMENT '操作前售后单状态',
  `after_state` int NULL COMMENT '操作后售后单状态',
  `operation_type` int NULL COMMENT '操作类型',
  `operation_content` varchar(255) NULL COMMENT '操作内容描述',
  `refund_amount` bigint NULL COMMENT '本次操作涉及的退款金额(落库 BIGINT 分, 与 refund 表口径一致)',
  `freight_company_name` varchar(255) NULL COMMENT '物流公司名称',
  `freight_no` varchar(255) NULL COMMENT '物流单号',
  `reason` varchar(255) NULL COMMENT '操作原因/备注',
  `ext` json NULL COMMENT '拓展字段',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`)
) COMMENT = '售后操作记录表 DO';
