ALTER TABLE
  `refund` DROP COLUMN `from_state`,
  DROP COLUMN `merchant_id`,
  DROP COLUMN `receive_address`,
  MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `order_id` bigint NULL COMMENT '交易单ID' AFTER `id`,
  MODIFY COLUMN `out_refund_id` varchar(255) NULL COMMENT '外部售后单号' AFTER `order_id`,
ADD
  COLUMN `create_role` bigint NULL COMMENT '申请人角色' AFTER `out_refund_id`,
  MODIFY COLUMN `order_type` int NULL COMMENT '订单类型' AFTER `create_role`,
  MODIFY COLUMN `spu_channel_type` int NULL COMMENT '渠道类型' AFTER `order_type`,
  MODIFY COLUMN `store_id` bigint NULL COMMENT '门店ID' AFTER `spu_channel_type`,
  MODIFY COLUMN `member_id` bigint NULL COMMENT '客户ID' AFTER `store_id`,
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'SPU订单ID' AFTER `member_id`,
  MODIFY COLUMN `channel_id` bigint NULL COMMENT '渠道商ID' AFTER `spu_order_id`,
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT '供应商ID' AFTER `channel_id`,
  MODIFY COLUMN `refund_state` int NULL COMMENT '售后状态',
  MODIFY COLUMN `refund_type` int NULL COMMENT '售后类型',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT '运费金额' AFTER `refund_type`,
  MODIFY COLUMN `refund_amount` bigint NULL COMMENT '退款金额' AFTER `freight_amount`,
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT '货款金额' AFTER `refund_amount`,
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT '选品金额' AFTER `supplier_amount`,
  MODIFY COLUMN `store_amount` bigint NULL COMMENT '铺货金额' AFTER `goods_amount`,
  MODIFY COLUMN `service_amount` bigint NULL COMMENT '服务费' AFTER `store_amount`,
  MODIFY COLUMN `reason` varchar(255) NULL COMMENT '售后原因' AFTER `service_amount`,
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT '备注' AFTER `reason`,
  MODIFY COLUMN `images` varchar(255) NULL COMMENT '凭证图片' AFTER `remark`,
  MODIFY COLUMN `phone` varchar(255) NULL COMMENT '联系电话' AFTER `images`,
  MODIFY COLUMN `freight_company_name` varchar(255) NULL COMMENT '物流公司名称' AFTER `phone`,
  MODIFY COLUMN `freight_no` varchar(255) NULL COMMENT '物流单号' AFTER `freight_company_name`,
  MODIFY COLUMN `take_delivery_state` int NULL COMMENT '收货状态(源列 take_delivery_state, 取值 0/1)' AFTER `freight_no`,
  MODIFY COLUMN `pay_state` int NULL COMMENT '退款支付状态(源列 pay_state, 取值 0/1)' AFTER `take_delivery_state`,
  MODIFY COLUMN `audit_time` datetime NULL COMMENT '审核时间' AFTER `pay_state`,
  MODIFY COLUMN `refund_time` datetime NULL COMMENT '退款完成时间' AFTER `audit_time`,
  MODIFY COLUMN `state_time` datetime NULL COMMENT '状态变化时间' AFTER `refund_time`,
  MODIFY COLUMN `store_auto_time` datetime NULL COMMENT '商家自动确认截止时间' AFTER `state_time`,
  MODIFY COLUMN `refund_state_log` varchar(255) NULL COMMENT '售后流转状态' AFTER `store_auto_time`,
  MODIFY COLUMN `from_order_state` int NULL COMMENT '来源订单状态' AFTER `refund_state_log`,
  MODIFY COLUMN `item` json NULL COMMENT '售后明细(JSON 结构 List&lt;RefundItemVO&gt;)' AFTER `from_order_state`,
  MODIFY COLUMN `refuse_reason` varchar(255) NULL COMMENT '拒绝原因' AFTER `item`,
ADD
  COLUMN `out_refund_address` varchar(255) NULL COMMENT '外部售后地址(JSON 结构 ApiRefundFreightAddressVO)' AFTER `refuse_reason`,
  MODIFY COLUMN `freight_ext` json NULL COMMENT '运费扩展信息' AFTER `out_refund_address`,
ADD
  COLUMN `executor` json NULL COMMENT '操作人信息' AFTER `freight_ext`,
ADD
  COLUMN `creator_id` bigint NULL COMMENT '创建人id' AFTER `executor`,
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
ADD
  COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
