ALTER TABLE
  `refund` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `order_id` bigint NULL COMMENT 'orderId',
  MODIFY COLUMN `out_refund_id` varchar(255) NULL COMMENT 'outRefundId',
  MODIFY COLUMN `create_role` int NULL COMMENT 'createRole[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `order_type` int NULL COMMENT 'orderType[0渠道商选品下单,1c端铺货下单,2运营商礼包下单]',
  MODIFY COLUMN `spu_channel_type` int NULL COMMENT 'spuChannelType[0供应商商品,2外部供应链商品]',
  MODIFY COLUMN `store_id` bigint NULL COMMENT 'storeId',
  MODIFY COLUMN `member_id` bigint NULL COMMENT 'memberId',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'spuOrderId',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT 'channelId',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT 'supplierId',
  MODIFY COLUMN `refund_state` int NULL COMMENT 'refundState',
  MODIFY COLUMN `refund_type` int NULL COMMENT 'refundType',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT 'freightAmount',
  MODIFY COLUMN `refund_amount` bigint NULL COMMENT 'refundAmount',
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT 'supplierAmount',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT 'goodsAmount',
  MODIFY COLUMN `store_amount` bigint NULL COMMENT 'storeAmount',
  MODIFY COLUMN `service_amount` bigint NULL COMMENT 'serviceAmount',
  MODIFY COLUMN `reason` varchar(255) NULL COMMENT 'reason',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT 'remark',
  MODIFY COLUMN `images` varchar(255) NULL COMMENT 'images',
  MODIFY COLUMN `phone` varchar(255) NULL COMMENT 'phone',
  MODIFY COLUMN `freight_company_name` varchar(255) NULL COMMENT 'freightCompanyName',
  MODIFY COLUMN `freight_no` varchar(255) NULL COMMENT 'freightNo',
  MODIFY COLUMN `take_delivery_state` int NULL COMMENT 'takeDeliveryState',
  MODIFY COLUMN `pay_state` int NULL COMMENT 'payState',
  MODIFY COLUMN `audit_time` datetime NULL COMMENT 'auditTime',
  MODIFY COLUMN `refund_time` datetime NULL COMMENT 'refundTime',
  MODIFY COLUMN `state_time` datetime NULL COMMENT 'stateTime',
  MODIFY COLUMN `store_auto_time` datetime NULL COMMENT 'storeAutoTime',
  MODIFY COLUMN `refund_state_log` varchar(255) NULL COMMENT 'refundStateLog',
  MODIFY COLUMN `from_order_state` int NULL COMMENT 'fromOrderState[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `item` json NULL COMMENT 'item',
  MODIFY COLUMN `refuse_reason` varchar(255) NULL COMMENT 'refuseReason',
  MODIFY COLUMN `out_refund_address` varchar(255) NULL COMMENT 'outRefundAddress',
  MODIFY COLUMN `freight_ext` json NULL COMMENT 'freightExt',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'RefundDO表';
