ALTER TABLE
  `refund` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `order_id` bigint NULL COMMENT '交易单ID',
  MODIFY COLUMN `out_refund_id` varchar(255) NULL COMMENT '外部售后单号',
  MODIFY COLUMN `create_role` int NULL COMMENT '申请人角色[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `order_type` int NULL COMMENT '订单类型[0渠道商选品下单,1c端铺货下单,2运营商礼包下单]',
  MODIFY COLUMN `spu_channel_type` int NULL COMMENT '渠道类型[0供应商商品,2外部供应链商品]',
  MODIFY COLUMN `store_id` bigint NULL COMMENT '门店ID',
  MODIFY COLUMN `member_id` bigint NULL COMMENT '客户ID',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'SPU订单ID',
  MODIFY COLUMN `channel_id` bigint NULL COMMENT '渠道商ID',
  MODIFY COLUMN `supplier_id` bigint NULL COMMENT '供应商ID',
  MODIFY COLUMN `refund_state` int NULL COMMENT '售后状态',
  MODIFY COLUMN `refund_type` int NULL COMMENT '售后类型',
  MODIFY COLUMN `freight_amount` bigint NULL COMMENT '运费金额',
  MODIFY COLUMN `refund_amount` bigint NULL COMMENT '退款金额',
  MODIFY COLUMN `supplier_amount` bigint NULL COMMENT '货款金额',
  MODIFY COLUMN `goods_amount` bigint NULL COMMENT '选品金额',
  MODIFY COLUMN `store_amount` bigint NULL COMMENT '铺货金额',
  MODIFY COLUMN `service_amount` bigint NULL COMMENT '服务费',
  MODIFY COLUMN `reason` varchar(255) NULL COMMENT '售后原因',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT '备注',
  MODIFY COLUMN `images` varchar(255) NULL COMMENT '凭证图片',
  MODIFY COLUMN `phone` varchar(255) NULL COMMENT '联系电话',
  MODIFY COLUMN `freight_company_name` varchar(255) NULL COMMENT '物流公司名称',
  MODIFY COLUMN `freight_no` varchar(255) NULL COMMENT '物流单号',
  MODIFY COLUMN `take_delivery_state` int NULL COMMENT '收货状态(源列 take_delivery_state, 取值 0/1)',
  MODIFY COLUMN `pay_state` int NULL COMMENT '退款支付状态(源列 pay_state, 取值 0/1)',
  MODIFY COLUMN `audit_time` datetime NULL COMMENT '审核时间',
  MODIFY COLUMN `refund_time` datetime NULL COMMENT '退款完成时间',
  MODIFY COLUMN `state_time` datetime NULL COMMENT '状态变化时间',
  MODIFY COLUMN `store_auto_time` datetime NULL COMMENT '商家自动确认截止时间',
  MODIFY COLUMN `refund_state_log` varchar(255) NULL COMMENT '售后流转状态',
  MODIFY COLUMN `from_order_state` int NULL COMMENT '来源订单状态[0新订单,1C端待付款,2渠道商待付款,3运营商待付款,4派发中,6待发货,8待收货,10已收货,12已完成,14售后中,99已关闭]',
  MODIFY COLUMN `item` json NULL COMMENT '售后明细(JSON 结构 List&lt;RefundItemVO&gt;)',
  MODIFY COLUMN `refuse_reason` varchar(255) NULL COMMENT '拒绝原因',
  MODIFY COLUMN `out_refund_address` varchar(255) NULL COMMENT '外部售后地址(JSON 结构 ApiRefundFreightAddressVO)',
  MODIFY COLUMN `freight_ext` json NULL COMMENT '运费扩展信息',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))';
