CREATE TABLE `refund` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NULL COMMENT '交易单ID',
  `out_refund_id` varchar(255) NULL COMMENT '外部售后单号',
  `create_role` bigint NULL COMMENT '申请人角色',
  `order_type` int NULL COMMENT '订单类型',
  `spu_channel_type` int NULL COMMENT '渠道类型',
  `store_id` bigint NULL COMMENT '门店ID',
  `member_id` bigint NULL COMMENT '客户ID',
  `spu_order_id` bigint NULL COMMENT 'SPU订单ID',
  `channel_id` bigint NULL COMMENT '渠道商ID',
  `supplier_id` bigint NULL COMMENT '供应商ID',
  `refund_state` int NULL COMMENT '售后状态',
  `refund_type` int NULL COMMENT '售后类型',
  `freight_amount` bigint NULL COMMENT '运费金额',
  `refund_amount` bigint NULL COMMENT '退款金额',
  `supplier_amount` bigint NULL COMMENT '货款金额',
  `goods_amount` bigint NULL COMMENT '选品金额',
  `store_amount` bigint NULL COMMENT '铺货金额',
  `service_amount` bigint NULL COMMENT '服务费',
  `reason` varchar(255) NULL COMMENT '售后原因',
  `remark` varchar(255) NULL COMMENT '备注',
  `images` varchar(255) NULL COMMENT '凭证图片',
  `phone` varchar(255) NULL COMMENT '联系电话',
  `freight_company_name` varchar(255) NULL COMMENT '物流公司名称',
  `freight_no` varchar(255) NULL COMMENT '物流单号',
  `take_delivery_state` int NULL COMMENT '收货状态(源列 take_delivery_state, 取值 0/1)',
  `pay_state` int NULL COMMENT '退款支付状态(源列 pay_state, 取值 0/1)',
  `audit_time` datetime NULL COMMENT '审核时间',
  `refund_time` datetime NULL COMMENT '退款完成时间',
  `state_time` datetime NULL COMMENT '状态变化时间',
  `store_auto_time` datetime NULL COMMENT '商家自动确认截止时间',
  `refund_state_log` varchar(255) NULL COMMENT '售后流转状态',
  `from_order_state` int NULL COMMENT '来源订单状态',
  `item` json NULL COMMENT '售后明细(JSON 结构 List&lt;RefundItemVO&gt;)',
  `refuse_reason` varchar(255) NULL COMMENT '拒绝原因',
  `out_refund_address` varchar(255) NULL COMMENT '外部售后地址(JSON 结构 ApiRefundFreightAddressVO)',
  `freight_ext` json NULL COMMENT '运费扩展信息',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`)
);
