ALTER TABLE
  `refund_operation_record` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'spuOrderId',
  MODIFY COLUMN `refund_id` bigint NULL COMMENT 'refundId',
  MODIFY COLUMN `operator_id` bigint NULL COMMENT 'operatorId',
  MODIFY COLUMN `operator_role_code` int NULL COMMENT 'operatorRoleCode[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `operator_client` varchar(11) NULL COMMENT 'operatorClient[admin平台端,user用户端,partner服务商端,channel渠道商端,supplier供应商端,mmt_channel脉脉通渠道商端]',
  MODIFY COLUMN `operator_name` varchar(255) NULL COMMENT 'operatorName',
  MODIFY COLUMN `before_state` int NULL COMMENT 'beforeState',
  MODIFY COLUMN `after_state` int NULL COMMENT 'afterState',
  MODIFY COLUMN `operation_type` int NULL COMMENT 'operationType',
  MODIFY COLUMN `operation_content` varchar(255) NULL COMMENT 'operationContent',
  MODIFY COLUMN `refund_amount` bigint NULL COMMENT 'refundAmount',
  MODIFY COLUMN `freight_company_name` varchar(255) NULL COMMENT 'freightCompanyName',
  MODIFY COLUMN `freight_no` varchar(255) NULL COMMENT 'freightNo',
  MODIFY COLUMN `reason` varchar(255) NULL COMMENT 'reason',
  MODIFY COLUMN `ext` json NULL COMMENT 'ext',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'RefundOperationRecordDO表';
