ALTER TABLE
  `refund_operation_record` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `spu_order_id` bigint NULL COMMENT 'spu订单id',
  MODIFY COLUMN `refund_id` bigint NULL COMMENT '售后单refund表的主键',
  MODIFY COLUMN `operator_id` bigint NULL COMMENT '操作人ID',
  MODIFY COLUMN `operator_role_code` int NULL COMMENT '操作方角色编码[1平台管理员,2平台员工,1000会员,1001供应商,1002渠道商,1003服务商,1004脉脉通渠道商]',
  MODIFY COLUMN `operator_client` varchar(11) NULL COMMENT '操作方客户端类型[admin平台端,user用户端,partner服务商端,channel渠道商端,supplier供应商端,mmt_channel脉脉通渠道商端]',
  MODIFY COLUMN `operator_name` varchar(255) NULL COMMENT '操作方名称',
  MODIFY COLUMN `before_state` int NULL COMMENT '操作前售后单状态',
  MODIFY COLUMN `after_state` int NULL COMMENT '操作后售后单状态',
  MODIFY COLUMN `operation_type` int NULL COMMENT '操作类型',
  MODIFY COLUMN `operation_content` varchar(255) NULL COMMENT '操作内容描述',
  MODIFY COLUMN `refund_amount` bigint NULL COMMENT '本次操作涉及的退款金额(落库 BIGINT 分, 与 refund 表口径一致)',
  MODIFY COLUMN `freight_company_name` varchar(255) NULL COMMENT '物流公司名称',
  MODIFY COLUMN `freight_no` varchar(255) NULL COMMENT '物流单号',
  MODIFY COLUMN `reason` varchar(255) NULL COMMENT '操作原因/备注',
  MODIFY COLUMN `ext` json NULL COMMENT '拓展字段(JSON 列, 对象直传)',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '售后操作记录表 DO';
