ALTER TABLE
  `course_purchase_record` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `order_no` bigint NULL COMMENT 'orderNo',
  MODIFY COLUMN `course_id` bigint NULL COMMENT 'courseId',
  MODIFY COLUMN `course_num` varchar(255) NULL COMMENT 'courseNum',
  MODIFY COLUMN `user_id` bigint NULL COMMENT 'userId',
  MODIFY COLUMN `original_price` bigint NULL COMMENT 'originalPrice',
  MODIFY COLUMN `pay_price` bigint NULL COMMENT 'payPrice',
  MODIFY COLUMN `pay_state` int NULL COMMENT 'payState',
  MODIFY COLUMN `pay_time` datetime NULL COMMENT 'payTime',
  MODIFY COLUMN `pay_type` int NULL COMMENT 'payType[0直接,1微信,2支付宝,3采购金,4兑换码]',
  MODIFY COLUMN `pay_no` varchar(255) NULL COMMENT 'payNo',
  MODIFY COLUMN `pay_url` varchar(255) NULL COMMENT 'payUrl',
  MODIFY COLUMN `expire_time` datetime NULL COMMENT 'expireTime',
  MODIFY COLUMN `cancel_time` datetime NULL COMMENT 'cancelTime',
  MODIFY COLUMN `remark` varchar(255) NULL COMMENT 'remark',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'CoursePurchaseRecordDO表';
