ALTER TABLE
  `course_chapter` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `course_id` bigint NULL COMMENT 'courseId',
  MODIFY COLUMN `title` varchar(255) NULL COMMENT 'title',
  MODIFY COLUMN `chapter_num` int NULL COMMENT 'chapterNum',
  MODIFY COLUMN `virtual_study_count` int NULL COMMENT 'virtualStudyCount',
  MODIFY COLUMN `is_free` int NULL COMMENT 'isFree[1是,0否]',
  MODIFY COLUMN `self_media_url` varchar(255) NULL COMMENT 'selfMediaUrl',
  MODIFY COLUMN `external_media_url` varchar(255) NULL COMMENT 'externalMediaUrl',
  MODIFY COLUMN `publish_time` datetime NULL COMMENT 'publishTime',
  MODIFY COLUMN `duration_centisecond` int NULL COMMENT 'durationCentisecond',
  MODIFY COLUMN `duration_desc` varchar(255) NULL COMMENT 'durationDesc',
  MODIFY COLUMN `is_enabled` int NULL COMMENT 'isEnabled[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'CourseChapterDO表';
