ALTER TABLE
  `course` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `course_num` varchar(255) NULL COMMENT 'courseNo',
  MODIFY COLUMN `title` varchar(255) NULL COMMENT 'title',
  MODIFY COLUMN `intro` varchar(255) NULL COMMENT 'intro',
  MODIFY COLUMN `lecturer_id` bigint NULL COMMENT 'lecturerId',
  MODIFY COLUMN `category_id` bigint NULL COMMENT 'categoryId',
  MODIFY COLUMN `original_price` bigint NULL COMMENT 'originalPrice',
  MODIFY COLUMN `sell_price` bigint NULL COMMENT 'sellPrice',
  MODIFY COLUMN `virtual_purchase_count` int NULL COMMENT 'virtualPurchaseCount',
  MODIFY COLUMN `purchase_count` int NULL COMMENT 'purchaseCount',
  MODIFY COLUMN `cover_image` varchar(255) NULL COMMENT 'coverImage',
  MODIFY COLUMN `carousel_images` varchar(255) NULL COMMENT 'carouselImages',
  MODIFY COLUMN `video_url` varchar(255) NULL COMMENT 'videoUrl',
  MODIFY COLUMN `details` varchar(255) NULL COMMENT 'details',
  MODIFY COLUMN `chapter_count` int NULL COMMENT 'chapterCount',
  MODIFY COLUMN `total_duration_centisecond` bigint NULL COMMENT 'totalDurationCentisecond',
  MODIFY COLUMN `total_duration_desc` varchar(255) NULL COMMENT 'totalDurationDesc',
  MODIFY COLUMN `is_enabled` int NULL COMMENT 'isEnabled[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'CourseDO表';
