<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.newzkl.platform.Base</groupId>
        <artifactId>biz-auth</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>biz-auth-infrastructure</artifactId>
    <packaging>jar</packaging>
    <name>biz-auth-infrastructure</name>
    <description>认证授权域实现: adapt/repository(RepositoryImpl) + adapt/api(port实现) + entity(DO) + dao(Mapper)</description>

    <dependencies>
        <dependency>
            <groupId>com.newzkl.platform.Base</groupId>
            <artifactId>biz-auth-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.newzkl.platform.Base</groupId>
            <artifactId>ddd-infrastructure</artifactId>
        </dependency>
    </dependencies>
</project>
