CREATE TABLE `bonus_pool_archive` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `bonus_pool_id` bigint NULL COMMENT '奖金池id',
  `channel_id` bigint NULL COMMENT '渠道商id',
  `activity_id` varchar(255) NULL COMMENT '活动id',
  `activity_name` varchar(255) NULL COMMENT '活动名称',
  `settlement_id` varchar(255) NULL COMMENT '结算id',
  `settlement_name` varchar(255) NULL COMMENT '结算名称',
  `order_info` varchar(255) NULL COMMENT '订单信息',
  `estimated_dividend` varchar(255) NULL COMMENT '预计分红',
  `actual_dividend` varchar(255) NULL COMMENT '实际分红',
  `pool_participant` varchar(255) NULL COMMENT '奖金池参与人员',
  `pool_participant_list` varchar(255) NULL COMMENT '奖金池参与人员id',
  `dividend_method` varchar(255) NULL COMMENT '分红方式',
  `dividend_cycle` varchar(255) NULL COMMENT '结算周期',
  `confirm_time` datetime NULL COMMENT '确认时间',
  `bonus_desc` varchar(255) NULL COMMENT '奖金池活动描述',
  `strategy_id` bigint NULL COMMENT '策略id',
  `other_config` bigint NULL COMMENT '其他配置',
  `order_bonus` bigint NULL COMMENT '订单奖金 (Money, 落库 BIGINT 分)',
  `custom_bonus` bigint NULL COMMENT '自定义奖金',
  `settle_bonus` bigint NULL COMMENT '最终结算奖金',
  `settle_type` int NULL COMMENT '结算方式(0-未结算, 1-订单, 2-自定义)',
  `state` varchar(255) NULL COMMENT '状态

{@link ActivityEnum.SettleState}',
  `dividend_status` varchar(255) NULL COMMENT '分红状态',
  `order_amounts_rate` int NULL COMMENT '订单金额占比',
  `start_time` date NULL COMMENT '开始时间',
  `end_time` date NULL COMMENT '结束时间',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`)
) COMMENT = '往期奖金池归档';
