ALTER TABLE
  `account` MODIFY COLUMN `id` bigint NOT NULL COMMENT '主键ID',
  MODIFY COLUMN `client` varchar(11) NOT NULL COMMENT '所属端[admin平台端,user用户端,partner服务商端,channel渠道商端,supplier供应商端,mmt_channel脉脉通渠道商端]',
  MODIFY COLUMN `pid` bigint NULL COMMENT '父ID',
  MODIFY COLUMN `pid_list` varchar(255) NULL COMMENT '父ID列表',
  MODIFY COLUMN `main_account_id` bigint NULL COMMENT '顶层主账号id (主账号自身=0, 子账号=顶层主账号id)',
  MODIFY COLUMN `origin` int NULL COMMENT '账号来源[1自行注册,2主账号创建,3邀请]',
  MODIFY COLUMN `nickname` varchar(255) NULL COMMENT '昵称',
  MODIFY COLUMN `username` varchar(255) NULL COMMENT '登录名称',
  MODIFY COLUMN `real_name` varchar(255) NULL COMMENT '真实姓名',
  MODIFY COLUMN `password` varchar(255) NULL COMMENT '密码',
  MODIFY COLUMN `state` int NULL COMMENT '状态[-1已注销,0已封禁,1正常]',
  MODIFY COLUMN `last_login_time` datetime NULL COMMENT '上次登录时间',
  MODIFY COLUMN `invite_account_id` bigint NULL COMMENT '邀请人ID',
  MODIFY COLUMN `identity_list` varchar(255) NULL COMMENT '角色ID集合',
  MODIFY COLUMN `yqm` varchar(255) NULL COMMENT '邀请码',
  MODIFY COLUMN `phone` varchar(255) NULL COMMENT '手机号',
  MODIFY COLUMN `head` varchar(255) NULL COMMENT '头像',
  MODIFY COLUMN `cancel_time` datetime NULL COMMENT '账号注销时间',
  MODIFY COLUMN `tripartite_account_permission` int NULL COMMENT '三方账户权限[1是,0否]',
  MODIFY COLUMN `tripartite_account_id` varchar(255) NULL COMMENT '三方账户id',
  MODIFY COLUMN `executor` json NULL COMMENT '操作人信息',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT '创建人id',
  MODIFY COLUMN `create_time` datetime NULL COMMENT '创建时间',
  MODIFY COLUMN `update_time` datetime NULL COMMENT '更新时间',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  COMMENT = '用户账号';
