CREATE TABLE `account` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `client` varchar(255) NOT NULL COMMENT '所属端',
  `main_account_id` bigint NULL COMMENT '主账号id',
  `pid` bigint NULL COMMENT '父ID',
  `pid_list` varchar(255) NULL COMMENT '父ID列表',
  `p_role_list` varchar(255) NULL COMMENT '父层级角色关系',
  `nickname` varchar(255) NULL COMMENT '昵称',
  `username` varchar(255) NULL COMMENT '登录名称',
  `sub_user_type` int NULL COMMENT '子用户类型',
  `real_name` varchar(255) NULL COMMENT '真实姓名',
  `password` varchar(255) NULL COMMENT '密码',
  `state` int NULL COMMENT '状态',
  `last_login_time` datetime NULL COMMENT '上次登录时间',
  `name_auth_audit_state` int NULL COMMENT '实名认证审批状态',
  `sub_account_count` int NULL COMMENT '子账号数量',
  `below_count` int NULL COMMENT '下级数量',
  `invite_account_id` bigint NULL COMMENT '邀请人ID',
  `role_id_list` varchar(255) NULL COMMENT '角色ID集合',
  `yqm` varchar(255) NULL COMMENT '邀请码',
  `phone` varchar(255) NULL COMMENT '手机号',
  `user_account` varchar(255) NULL COMMENT '账号(tencent IM 用)',
  `im_sync_status` int NULL COMMENT 'IM同步状态(0-未同步, 1-已同步, 2-同步失败)',
  `head` varchar(255) NULL COMMENT '头像',
  `cancel_time` datetime NULL COMMENT '账号注销时间',
  `tripartite_account_permission` int NULL COMMENT '三方账户权限',
  `tripartite_account_id` varchar(255) NULL COMMENT '三方账户id',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`, `client`),
  INDEX `auto_idx_account_invite_account_id`(`invite_account_id`) COMMENT '邀请人ID',
  INDEX `auto_idx_account_phone`(`phone`) COMMENT '手机号',
  INDEX `auto_idx_account_pid_list`(`pid_list`) COMMENT '父ID列表',
  INDEX `auto_idx_account_pid`(`pid`) COMMENT '父ID',
  INDEX `auto_idx_account_username`(`username`) COMMENT '登录名称'
) COMMENT = '用户账号';
