ALTER TABLE
  `account` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `client` varchar(11) NOT NULL COMMENT 'client[admin平台端,user用户端,partner服务商端,channel渠道商端,supplier供应商端,mmt_channel脉脉通渠道商端]',
  MODIFY COLUMN `pid` bigint NULL COMMENT 'pid',
  MODIFY COLUMN `pid_list` varchar(255) NULL COMMENT 'pidList',
  MODIFY COLUMN `main_account_id` bigint NULL COMMENT 'mainAccountId',
  MODIFY COLUMN `origin` int NULL COMMENT 'origin[1自行注册,2主账号创建,3邀请]',
  MODIFY COLUMN `nickname` varchar(255) NULL COMMENT 'nickname',
  MODIFY COLUMN `username` varchar(255) NULL COMMENT 'username',
  MODIFY COLUMN `real_name` varchar(255) NULL COMMENT 'realName',
  MODIFY COLUMN `password` varchar(255) NULL COMMENT 'password',
  MODIFY COLUMN `state` int NULL COMMENT 'state[-1已注销,0已封禁,1正常]',
  MODIFY COLUMN `last_login_time` datetime NULL COMMENT 'lastLoginTime',
  MODIFY COLUMN `invite_account_id` bigint NULL COMMENT 'inviteAccountId',
  MODIFY COLUMN `identity_list` varchar(255) NULL COMMENT 'identityList',
  MODIFY COLUMN `yqm` varchar(255) NULL COMMENT 'yqm',
  MODIFY COLUMN `phone` varchar(255) NULL COMMENT 'phone',
  MODIFY COLUMN `head` varchar(255) NULL COMMENT 'head',
  MODIFY COLUMN `cancel_time` datetime NULL COMMENT 'cancelTime',
  MODIFY COLUMN `tripartite_account_permission` int NULL COMMENT 'tripartiteAccountPermission[1是,0否]',
  MODIFY COLUMN `tripartite_account_id` varchar(255) NULL COMMENT 'tripartiteAccountId',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'AccountDO表';
