ALTER TABLE
  `lecturer` MODIFY COLUMN `id` bigint NOT NULL COMMENT 'id',
  MODIFY COLUMN `lecturer_name` varchar(255) NULL COMMENT 'lecturerName',
  MODIFY COLUMN `main_account` varchar(255) NULL COMMENT 'mainAccount',
  MODIFY COLUMN `main_account_id` bigint NULL COMMENT 'mainAccountId',
  MODIFY COLUMN `lecturer_category_id` bigint NULL COMMENT 'lecturerCategoryId',
  MODIFY COLUMN `lecturer_category_name` varchar(255) NULL COMMENT 'lecturerCategoryName',
  MODIFY COLUMN `course_count` int NULL COMMENT 'courseCount',
  MODIFY COLUMN `follow_count` int NULL COMMENT 'followCount',
  MODIFY COLUMN `personal_intro` varchar(255) NULL COMMENT 'personalIntro',
  MODIFY COLUMN `cover_image_url` varchar(255) NULL COMMENT 'coverImageUrl',
  MODIFY COLUMN `avatar_url` varchar(255) NULL COMMENT 'avatarUrl',
  MODIFY COLUMN `is_enabled` int NULL COMMENT 'isEnabled[1是,0否]',
  MODIFY COLUMN `executor` json NULL COMMENT 'executor',
  MODIFY COLUMN `creator_id` bigint NULL COMMENT 'creatorId',
  MODIFY COLUMN `create_time` datetime NULL COMMENT 'createTime',
  MODIFY COLUMN `update_time` datetime NULL COMMENT 'updateTime',
  MODIFY COLUMN `del_flag` int NULL DEFAULT 0 COMMENT 'delFlag',
  COMMENT = 'LecturerDO表';
