CREATE TABLE `lecturer` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `lecturer_name` varchar(255) NULL COMMENT '讲师名称(即渠道商名称)',
  `main_account` varchar(255) NULL COMMENT '主体账号(展示用字符串)',
  `main_account_id` bigint NULL COMMENT '主体账号ID(关联主体账号表主键)',
  `lecturer_category_id` bigint NULL COMMENT '讲师分类ID(关联讲师分类表主键)',
  `lecturer_category_name` varchar(255) NULL COMMENT '讲师分类名称(冗余存储便于展示)',
  `course_count` int NULL COMMENT '课程数量',
  `follow_count` int NULL COMMENT '被关注人数累计值',
  `personal_intro` varchar(255) NULL COMMENT '个人简介',
  `cover_image_url` varchar(255) NULL COMMENT '封面图URL',
  `avatar_url` varchar(255) NULL COMMENT '头像URL',
  `is_enabled` int NULL COMMENT '是否启用(0-禁用, 1-启用)',
  `executor` json NULL COMMENT '操作人信息',
  `creator_id` bigint NULL COMMENT '创建人id',
  `create_time` datetime NULL COMMENT '创建时间',
  `update_time` datetime NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '逻辑删除标记(正常 0, 删除为 NULL(确保唯一索引生效))',
  PRIMARY KEY (`id`)
) COMMENT = '讲师数据对象';
